/* «Для чайника» — простые объяснения общих концепций (не глубина, а понимание сути).
   window.BASICS = [{id, g, icon, t, plain, an, en:{t,plain,an}}]  g — группа. */
window.BASICS = [
/* ───────── Данные ───────── */
{ id:"b-db", g:"Данные", icon:"🗄️", t:"База данных (БД)",
  plain:"Место, где приложение хранит данные надолго — они не пропадают после перезапуска. Ты кладёшь туда записи и достаёшь их по запросу.",
  an:"Как большой архив-склад: положил папку — потом в любой момент нашёл и забрал.",
  en:{ t:"Database (DB)", plain:"Where an app stores data for the long term — it survives restarts. You put records in and fetch them by query.", an:"Like a big archive warehouse: file a folder once, retrieve it anytime later." } },
{ id:"b-table", g:"Данные", icon:"📊", t:"Таблица, строка, колонка",
  plain:"В обычной (реляционной) БД данные лежат таблицами. Колонки — это поля (имя, возраст), строки — конкретные записи.",
  an:"Как таблица в Excel: шапка сверху — колонки, каждая строчка ниже — один клиент.",
  en:{ t:"Table, row, column", plain:"In a relational DB data lives in tables. Columns are fields (name, age); rows are individual records.", an:"Like an Excel sheet: the header row is columns, each line below is one customer." } },
{ id:"b-index", g:"Данные", icon:"🔖", t:"Индекс",
  plain:"Отдельная структура, чтобы БД находила нужные строки быстро, не перебирая всю таблицу. Без него поиск в миллионах строк — медленный.",
  an:"Как оглавление в книге: не листаешь все 800 страниц, а сразу открываешь нужную.",
  en:{ t:"Index", plain:"A side structure so the DB finds rows fast without scanning the whole table. Without it, searching millions of rows is slow.", an:"Like a book's table of contents: you jump to the page instead of flipping all 800." } },
{ id:"b-tx", g:"Данные", icon:"🔒", t:"Транзакция",
  plain:"Группа операций, которые выполняются «всё или ничего». Если посреди что-то сломалось — откатывается всё, будто ничего и не было.",
  an:"Перевод денег: списать у одного и зачислить другому — либо оба шага, либо ни одного.",
  en:{ t:"Transaction", plain:"A group of operations that run all-or-nothing. If something breaks midway, everything rolls back as if it never happened.", an:"A money transfer: debit one and credit the other — either both steps or neither." } },
{ id:"b-cache", g:"Данные", icon:"⚡", t:"Кэш",
  plain:"Быстрое временное хранилище для того, что часто спрашивают, чтобы не бегать каждый раз в медленную БД. Данные там живут недолго.",
  an:"Блокнот под рукой: часто нужный телефон записал рядом, а не лезешь каждый раз в толстую записную книжку.",
  en:{ t:"Cache", plain:"Fast temporary storage for frequently requested things, so you don't hit the slow DB every time. Data there is short-lived.", an:"A sticky note at hand: the number you need often is right there, not deep in the fat address book." } },
{ id:"b-sql-nosql", g:"Данные", icon:"🗂️", t:"SQL vs NoSQL",
  plain:"SQL — строгие таблицы со связями и языком запросов SQL. NoSQL — гибкие документы/пары ключ-значение, когда структура разная или нужна огромная скорость/масштаб.",
  an:"SQL — картотека с жёсткими бланками; NoSQL — коробка, куда кидаешь разные листки как есть.",
  en:{ t:"SQL vs NoSQL", plain:"SQL — strict related tables with the SQL query language. NoSQL — flexible documents/key-value, for varying structure or huge speed/scale.", an:"SQL is a card index with rigid forms; NoSQL is a box you toss varied notes into as-is." } },
{ id:"b-key", g:"Данные", icon:"🗝️", t:"Первичный и внешний ключ",
  plain:"Первичный ключ — уникальный номер строки (id). Внешний ключ — ссылка из одной таблицы на строку в другой, так таблицы связываются.",
  an:"Первичный — номер паспорта; внешний — когда в договоре указан этот номер, чтобы понять, чей он.",
  en:{ t:"Primary & foreign key", plain:"A primary key is a row's unique id. A foreign key is a reference from one table to a row in another — that's how tables link.", an:"Primary = a passport number; foreign = a contract citing that number to say whose it is." } },

/* ───────── Связь ───────── */
{ id:"b-api", g:"Связь", icon:"🔌", t:"API",
  plain:"Набор «розеток», через которые одна программа просит другую что-то сделать или дать данные — по заранее оговорённым правилам.",
  an:"Как розетка в стене: не знаешь, как устроена электростанция, но втыкаешь вилку по стандарту — и работает.",
  en:{ t:"API", plain:"A set of 'sockets' one program uses to ask another to do something or return data — by agreed rules.", an:"Like a wall socket: you don't know how the power plant works, but the standard plug just fits and works." } },
{ id:"b-rest", g:"Связь", icon:"🌐", t:"REST",
  plain:"Популярный стиль API поверх HTTP: у каждой сущности есть адрес (URL), а действия — это методы GET (прочитать), POST (создать), PUT (изменить), DELETE (удалить).",
  an:"Как работа с сайтом: открыть страницу (GET), отправить форму (POST) — только для программ.",
  en:{ t:"REST", plain:"A popular API style over HTTP: each thing has an address (URL), and actions are methods GET (read), POST (create), PUT (update), DELETE (remove).", an:"Like using a website: open a page (GET), submit a form (POST) — but for programs." } },
{ id:"b-http", g:"Связь", icon:"📨", t:"HTTP-запрос и ответ",
  plain:"Язык, на котором клиент и сервер общаются в вебе. Клиент шлёт запрос (что хочу), сервер отвечает ответом и кодом статуса (200 — ок, 404 — не найдено, 500 — ошибка сервера).",
  an:"Письмо и ответ: отправил запрос-конверт — получил конверт-ответ с пометкой «доставлено» или «адрес не найден».",
  en:{ t:"HTTP request & response", plain:"The language clients and servers use on the web. The client sends a request (what I want); the server replies with a response and a status code (200 ok, 404 not found, 500 server error).", an:"A letter and reply: send a request envelope, get a reply stamped 'delivered' or 'address not found'." } },
{ id:"b-json", g:"Связь", icon:"📋", t:"JSON",
  plain:"Простой текстовый формат для обмена данными между программами — пары «ключ: значение». Его легко читают и человек, и машина.",
  an:"Как заполненная анкета: имя — Иван, возраст — 30. Понятно и тебе, и компьютеру.",
  en:{ t:"JSON", plain:"A simple text format to exchange data between programs — 'key: value' pairs. Easy for both humans and machines to read.", an:"Like a filled form: name — Ivan, age — 30. Clear to you and the computer alike." } },
{ id:"b-client-server", g:"Связь", icon:"🙋", t:"Клиент и сервер",
  plain:"Клиент — тот, кто просит (браузер, приложение на телефоне). Сервер — тот, кто принимает запросы и отвечает. Один сервер обслуживает много клиентов.",
  an:"Клиент — посетитель кафе, сервер — кухня: ты заказываешь, кухня готовит и выдаёт.",
  en:{ t:"Client and server", plain:"The client asks (a browser, a phone app). The server takes requests and responds. One server serves many clients.", an:"Client — a café guest; server — the kitchen: you order, the kitchen cooks and serves." } },
{ id:"b-queue", g:"Связь", icon:"📥", t:"Очередь сообщений",
  plain:"Буфер между сервисами: один кладёт задачи, другой забирает и обрабатывает в своём темпе. Помогает пережить всплески нагрузки и не терять задачи.",
  an:"Лента заказов на кухне: официанты вешают чеки, повар снимает по одному — никто никого не ждёт вплотную.",
  en:{ t:"Message queue", plain:"A buffer between services: one puts tasks in, another takes them out and processes at its own pace. Absorbs load spikes and avoids losing tasks.", an:"A kitchen order rail: waiters clip tickets, the cook takes them one by one — nobody blocks the other." } },
{ id:"b-micro-mono", g:"Связь", icon:"🧩", t:"Монолит vs микросервисы",
  plain:"Монолит — всё приложение одним куском. Микросервисы — много маленьких сервисов, каждый про своё, общаются по сети. Микро гибче масштабировать, но сложнее в эксплуатации.",
  an:"Монолит — один большой универмаг; микросервисы — улица из маленьких специализированных лавок.",
  en:{ t:"Monolith vs microservices", plain:"A monolith is the whole app in one piece. Microservices are many small services, each doing one thing, talking over the network. Micro scales more flexibly but is harder to operate.", an:"Monolith — one big department store; microservices — a street of small specialized shops." } },

/* ───────── Параллелизм ───────── */
{ id:"b-thread", g:"Параллелизм", icon:"🧵", t:"Поток (thread)",
  plain:"Отдельная линия выполнения внутри программы. Несколько потоков работают как бы одновременно, чтобы делать несколько дел сразу.",
  an:"Несколько касс в магазине: покупатели обслуживаются параллельно, а не в одной длинной очереди.",
  en:{ t:"Thread", plain:"A separate line of execution inside a program. Several threads run seemingly at once, so the app does multiple things in parallel.", an:"Several checkout lanes in a store: shoppers are served in parallel, not in one long line." } },
{ id:"b-lock", g:"Параллелизм", icon:"🚦", t:"Блокировка (lock)",
  plain:"Механизм «занято»: пока один поток меняет общие данные, другие ждут. Не даёт двоим одновременно испортить одно и то же.",
  an:"Замок на двери туалета: пока занято — остальные ждут снаружи.",
  en:{ t:"Lock", plain:"An 'occupied' mechanism: while one thread changes shared data, others wait. Stops two from corrupting the same thing at once.", an:"A restroom door lock: while occupied, others wait outside." } },
{ id:"b-race", g:"Параллелизм", icon:"💥", t:"Гонка (race condition)",
  plain:"Баг, когда два потока лезут к общим данным одновременно и результат зависит от того, кто успел первым. Итог — каша и непредсказуемость.",
  an:"Двое пишут в одну тетрадь одновременно поверх друг друга — получается нечитаемо.",
  en:{ t:"Race condition", plain:"A bug where two threads touch shared data at once and the result depends on who got there first. Outcome — mess and unpredictability.", an:"Two people writing in the same notebook at once, over each other — unreadable." } },
{ id:"b-sync-async", g:"Параллелизм", icon:"⏳", t:"Синхронно vs асинхронно",
  plain:"Синхронно — вызвал и ждёшь ответа, ничего больше не делая. Асинхронно — запустил, занялся другим, а результат заберёшь, когда будет готов.",
  an:"Синхронно — стоять у микроволновки; асинхронно — поставить и пойти заниматься делами, вернуться на «пиньк».",
  en:{ t:"Sync vs async", plain:"Sync — you call and wait for the reply, doing nothing else. Async — you start it, go do other things, and pick up the result when it's ready.", an:"Sync — standing by the microwave; async — start it, go do chores, come back on the 'ding'." } },
{ id:"b-pool", g:"Параллелизм", icon:"👷", t:"Пул потоков",
  plain:"Заранее созданная бригада потоков, которая разбирает задачи из очереди. Создавать поток на каждую задачу дорого, поэтому их переиспользуют.",
  an:"Бригада грузчиков: заявки приходят — свободный берёт следующую, а не нанимаешь нового под каждую коробку.",
  en:{ t:"Thread pool", plain:"A pre-created crew of threads that pick tasks from a queue. Spawning a thread per task is costly, so they're reused.", an:"A crew of movers: jobs come in, a free one grabs the next — you don't hire a new person per box." } },

/* ───────── Веб · безопасность ───────── */
{ id:"b-authn-authz", g:"Веб · безопасность", icon:"🪪", t:"Аутентификация vs авторизация",
  plain:"Аутентификация — кто ты (проверка логина/пароля). Авторизация — что тебе можно (какие действия и данные доступны). Сначала первое, потом второе.",
  an:"На входе в офис: охрана проверяет пропуск (кто ты) — потом смотрит, в какие двери он открывает (что можно).",
  en:{ t:"Authentication vs authorization", plain:"Authentication — who you are (checking login/password). Authorization — what you're allowed (which actions and data). First one, then the other.", an:"At an office door: the guard checks your badge (who), then which doors it opens (what you may)." } },
{ id:"b-jwt", g:"Веб · безопасность", icon:"🎫", t:"Токен (JWT)",
  plain:"Пропуск, который сервер выдаёт после входа. Клиент прикладывает его к каждому запросу, и сервер по подписи убеждается, что токен настоящий — не надо каждый раз вводить пароль.",
  an:"Браслет на фестивале: получил на входе один раз — дальше просто показываешь, а не покупаешь билет заново.",
  en:{ t:"Token (JWT)", plain:"A pass the server issues after login. The client attaches it to every request, and the server verifies its signature is genuine — no re-entering the password each time.", an:"A festival wristband: get it once at the gate — then just show it, no re-buying tickets." } },
{ id:"b-https", g:"Веб · безопасность", icon:"🔐", t:"HTTPS / TLS",
  plain:"Шифрование связи между браузером и сервером. Данные едут в «запечатанном конверте», чтобы по дороге их нельзя было прочитать или подменить.",
  an:"Заказное письмо в запечатанном конверте вместо открытки, которую по пути все читают.",
  en:{ t:"HTTPS / TLS", plain:"Encryption of the link between browser and server. Data travels in a 'sealed envelope' so it can't be read or tampered with on the way.", an:"A sealed registered letter instead of a postcard everyone reads en route." } },
{ id:"b-cookie", g:"Веб · безопасность", icon:"🍪", t:"Cookie и сессия",
  plain:"HTTP сам по себе не помнит тебя между запросами. Cookie — маленькая метка в браузере, по которой сервер узнаёт «это снова ты» и держит сессию (что ты залогинен).",
  an:"Номерок из гардероба: сервер не помнит лиц, но по номерку выдаёт именно твоё пальто.",
  en:{ t:"Cookie & session", plain:"HTTP by itself doesn't remember you between requests. A cookie is a small tag in the browser by which the server recognizes 'it's you again' and keeps a session (that you're logged in).", an:"A coat-check tag: the server doesn't recall faces, but the tag returns exactly your coat." } },

/* ───────── Инфраструктура ───────── */
{ id:"b-server", g:"Инфраструктура", icon:"🖥️", t:"Сервер",
  plain:"Компьютер, который всё время включён и ждёт запросы, чтобы на них отвечать. На нём крутится твоё приложение, доступное другим по сети.",
  an:"Круглосуточный киоск: всегда открыт, подходишь с вопросом — тебе отвечают.",
  en:{ t:"Server", plain:"A computer that's always on, waiting for requests to answer. Your app runs on it, reachable by others over the network.", an:"A 24/7 kiosk: always open — you come with a request, you get a reply." } },
{ id:"b-container", g:"Инфраструктура", icon:"📦", t:"Контейнер (Docker)",
  plain:"Коробка, в которую упаковано приложение вместе со всем, что ему нужно для запуска. Работает одинаково на ноутбуке и на сервере — «у меня-то работает» больше не проблема.",
  an:"Морской контейнер: что внутри упаковал — то и приедет целым на любой корабль и порт.",
  en:{ t:"Container (Docker)", plain:"A box packing the app together with everything it needs to run. Behaves the same on a laptop and a server — 'works on my machine' stops being a problem.", an:"A shipping container: whatever you packed arrives intact on any ship and port." } },
{ id:"b-k8s", g:"Инфраструктура", icon:"🚢", t:"Kubernetes",
  plain:"Управляющий сотнями контейнеров: сам запускает, перезапускает упавшие, добавляет копии под нагрузкой и распределяет их по серверам.",
  an:"Диспетчер порта: следит за всеми контейнерами, куда какой поставить, и заменяет повреждённые.",
  en:{ t:"Kubernetes", plain:"A manager of hundreds of containers: it starts them, restarts crashed ones, adds copies under load, and spreads them across servers.", an:"A port dispatcher: tracks all containers, places each one, and replaces damaged ones." } },
{ id:"b-lb", g:"Инфраструктура", icon:"⚖️", t:"Балансировщик нагрузки",
  plain:"Раздаёт входящие запросы между несколькими одинаковыми серверами, чтобы ни один не перегрузился. Если один упал — шлёт на живые.",
  an:"Администратор на входе, который направляет очередь к свободным кассам поровну.",
  en:{ t:"Load balancer", plain:"Spreads incoming requests across several identical servers so none gets overloaded. If one dies, it routes to the living ones.", an:"A host at the door directing the queue evenly to free checkouts." } },
{ id:"b-cicd", g:"Инфраструктура", icon:"🔧", t:"CI/CD",
  plain:"Конвейер, который автоматически собирает код, прогоняет тесты и выкатывает новую версию. Меньше ручных шагов — меньше ошибок и быстрее релизы.",
  an:"Заводской конвейер: деталь едет сама через сборку, проверку и упаковку — без ручного перетаскивания.",
  en:{ t:"CI/CD", plain:"A pipeline that automatically builds the code, runs tests, and ships the new version. Fewer manual steps — fewer errors and faster releases.", an:"A factory conveyor: the part moves itself through assembly, checks, and packaging — no manual hauling." } },
{ id:"b-observ", g:"Инфраструктура", icon:"📈", t:"Логи и метрики",
  plain:"Логи — дневник событий приложения (что и когда случилось). Метрики — числовые датчики (запросов в секунду, ошибок, задержка). Вместе — чтобы понять, что происходит и где сломалось.",
  an:"Логи — бортовой журнал корабля; метрики — приборная панель со стрелками.",
  en:{ t:"Logs & metrics", plain:"Logs — the app's event diary (what happened and when). Metrics — numeric gauges (requests/sec, errors, latency). Together they tell you what's going on and where it broke.", an:"Logs are the ship's logbook; metrics are the dashboard dials." } },
{ id:"b-cloud", g:"Инфраструктура", icon:"☁️", t:"Облако",
  plain:"Чужие серверы, которые ты арендуешь по мере надобности вместо покупки своих. Платишь за использование, масштабируешь кнопкой.",
  an:"Каршеринг вместо покупки машины: берёшь когда нужно, платишь за поездку, не думаешь о гараже.",
  en:{ t:"Cloud", plain:"Someone else's servers you rent as needed instead of buying your own. You pay for usage and scale with a button.", an:"Car-sharing instead of owning a car: take it when needed, pay per trip, no garage to worry about." } },

/* ───────── Код · Java ───────── */
{ id:"b-class-obj", g:"Код · Java", icon:"🏗️", t:"Класс и объект",
  plain:"Класс — чертёж (какие поля и что умеет). Объект — конкретное изделие по этому чертежу. Из одного класса делают много объектов.",
  an:"Класс — форма для печенья; объекты — сами печеньки, каждая отдельная.",
  en:{ t:"Class and object", plain:"A class is a blueprint (what fields and behaviors). An object is a concrete instance made from it. One class → many objects.", an:"A class is a cookie cutter; objects are the cookies, each its own." } },
{ id:"b-var-type", g:"Код · Java", icon:"🏷️", t:"Переменная и тип",
  plain:"Переменная — именованная коробка для значения. Тип задаёт, что в ней лежит (число, текст, дата) и что с этим можно делать.",
  an:"Подписанная банка на кухне: «сахар» — и туда не насыпешь болты.",
  en:{ t:"Variable and type", plain:"A variable is a named box for a value. The type says what it holds (number, text, date) and what you can do with it.", an:"A labeled kitchen jar: 'sugar' — you won't pour bolts into it." } },
{ id:"b-method", g:"Код · Java", icon:"⚙️", t:"Метод (функция)",
  plain:"Именованный кусок кода, который делает одно действие, часто принимает вход и возвращает результат. Вызываешь по имени вместо копирования кода.",
  an:"Кнопка на технике: «сделать эспрессо» — нажал, получил результат, не вникая в детали внутри.",
  en:{ t:"Method (function)", plain:"A named chunk of code that does one action, often takes input and returns a result. You call it by name instead of copying code.", an:"A button on a machine: 'make espresso' — press, get the result, no need to know the internals." } },
{ id:"b-exception", g:"Код · Java", icon:"🚨", t:"Исключение (exception)",
  plain:"Сигнал «что-то пошло не так» во время работы программы (нет файла, делёж на ноль). Его можно поймать и обработать, иначе программа падает.",
  an:"Пожарная сигнализация: сработала — либо ты реагируешь по плану, либо всё останавливается.",
  en:{ t:"Exception", plain:"A 'something went wrong' signal at runtime (missing file, divide by zero). You can catch and handle it, otherwise the program crashes.", an:"A fire alarm: once it goes off, either you act on a plan or everything halts." } },
{ id:"b-gc", g:"Код · Java", icon:"🧹", t:"Сборщик мусора (GC)",
  plain:"В Java память освобождается сама: сборщик мусора находит объекты, на которые больше никто не ссылается, и убирает их. Тебе не нужно вручную удалять память.",
  an:"Уборщик в опенспейсе: сам выносит то, чем никто уже не пользуется, — ты не думаешь про мусор.",
  en:{ t:"Garbage collector (GC)", plain:"In Java memory frees itself: the garbage collector finds objects nobody references anymore and removes them. You don't free memory by hand.", an:"An office cleaner: quietly hauls away what no one uses — you never think about the trash." } },
{ id:"b-interface", g:"Код · Java", icon:"🤝", t:"Интерфейс",
  plain:"Контракт «что должно уметь», без описания «как». Разные классы реализуют его по-своему, а код, который им пользуется, не зависит от деталей.",
  an:"Стандарт розетки: любой прибор с такой вилкой воткнётся, а как он устроен внутри — неважно.",
  en:{ t:"Interface", plain:"A contract of 'what it must do', without saying 'how'. Different classes implement it their own way, and code using them doesn't depend on the details.", an:"A socket standard: any device with the right plug fits; its internals don't matter." } },
{ id:"b-compile", g:"Код · Java", icon:"🔄", t:"Компиляция vs интерпретация",
  plain:"Компиляция — код заранее переводится в форму, понятную машине. Интерпретация — переводится на ходу, строчка за строчкой. Java сначала компилируется в байткод, а потом его исполняет JVM.",
  an:"Компиляция — заранее переведённая книга; интерпретация — переводчик рядом, переводит по фразе на ходу.",
  en:{ t:"Compilation vs interpretation", plain:"Compilation — code is translated ahead into machine-friendly form. Interpretation — translated on the fly, line by line. Java first compiles to bytecode, then the JVM runs it.", an:"Compilation — a pre-translated book; interpretation — an interpreter beside you, phrase by phrase." } },

{ id:"b-inherit", g:"Код · Java", icon:"🧬", t:"Наследование",
  plain:"Класс может «унаследовать» поля и методы другого класса и добавить/изменить своё. Общий код пишут в родителе, частности — в наследниках.",
  an:"Спорткар наследует от «машины» колёса и руль, но добавляет турбину — не изобретает машину заново.",
  en:{ t:"Inheritance", plain:"A class can 'inherit' another class's fields and methods and add/change its own. Common code lives in the parent, specifics in the children.", an:"A sports car inherits wheels and a steering wheel from 'car', but adds a turbo — it doesn't reinvent the car." } },
{ id:"b-polymorph", g:"Код · Java", icon:"🎭", t:"Полиморфизм",
  plain:"Один вызов метода работает по-разному в зависимости от реального объекта. Код зовёт draw(), а фигура сама знает, круг она или квадрат.",
  an:"Команда «издай звук» — кошка мяукнет, собака гавкнет. Приказ один, поведение зависит от того, кто его получил.",
  en:{ t:"Polymorphism", plain:"One method call behaves differently depending on the actual object. Code calls draw(), and the shape itself knows whether it's a circle or a square.", an:"The command 'make a sound' — a cat meows, a dog barks. One order, behavior depends on who receives it." } },
{ id:"b-encapsul", g:"Код · Java", icon:"🔒", t:"Инкапсуляция",
  plain:"Прятать внутренние данные объекта и давать доступ только через методы. Снаружи дёргают кнопки, а не лезут в кишки — так объект защищает своё состояние.",
  an:"Банкомат: ты нажимаешь кнопки, но к деньгам и проводам внутри доступа нет — только через разрешённые операции.",
  en:{ t:"Encapsulation", plain:"Hide an object's internal data and expose it only through methods. Outside you press buttons, not poke the guts — so the object protects its state.", an:"An ATM: you press buttons, but the cash and wiring inside are off-limits — only through allowed operations." } },
{ id:"b-immutable", g:"Код · Java", icon:"🧊", t:"Неизменяемость (immutable)",
  plain:"Неизменяемый объект нельзя поменять после создания — любое «изменение» создаёт новый объект. Такие объекты безопасны в многопотоке и предсказуемы (String в Java такой).",
  an:"Выгравированная табличка: хочешь другой текст — делаешь новую, старую не переправить.",
  en:{ t:"Immutability", plain:"An immutable object can't be changed after creation — any 'change' makes a new object. Such objects are thread-safe and predictable (Java's String is one).", an:"An engraved plaque: want different text — you make a new one, you can't edit the old." } },
{ id:"b-null-npe", g:"Код · Java", icon:"⛳", t:"null и NullPointerException",
  plain:"null — «здесь ничего нет», отсутствие объекта. Если позвать метод у null-ссылки, программа падает с NullPointerException — самой частой ошибкой Java. Помогают проверки и Optional.",
  an:"Пустая ячейка на почте: пытаешься достать посылку, а там ничего — рука проваливается.",
  en:{ t:"null and NullPointerException", plain:"null means 'nothing is here', the absence of an object. Calling a method on a null reference crashes with NullPointerException — Java's most common error. Null checks and Optional help.", an:"An empty mailbox slot: you reach for a parcel, but there's nothing — your hand goes through." } },
{ id:"b-stack-heap", g:"Код · Java", icon:"🗃️", t:"Стек и куча (память)",
  plain:"Стек — быстрая память для вызовов методов и локальных переменных, живёт недолго и сам сворачивается. Куча — общая память для объектов, которую убирает сборщик мусора.",
  an:"Стек — стопка подносов у метода (взял-положил-убрал); куча — большой склад объектов, где прибирается уборщик.",
  en:{ t:"Stack and heap (memory)", plain:"The stack is fast memory for method calls and local variables — short-lived and self-unwinding. The heap is shared memory for objects, cleaned by the garbage collector.", an:"The stack is a pile of trays per method (take, use, remove); the heap is a big object warehouse tidied by a cleaner." } },
{ id:"b-deadlock", g:"Параллелизм", icon:"🔗", t:"Взаимная блокировка (deadlock)",
  plain:"Два потока ждут друг друга и оба стоят навсегда: первый держит замок A и ждёт B, второй держит B и ждёт A. Лечится единым порядком захвата замков.",
  an:"Два человека в узком коридоре уступают друг другу «только после вас» — и оба стоят вечно.",
  en:{ t:"Deadlock", plain:"Two threads wait on each other and both freeze forever: one holds lock A and waits for B, the other holds B and waits for A. Fixed by always acquiring locks in the same order.", an:"Two people in a narrow hallway each say 'after you' — and both stand there forever." } },
{ id:"b-acid", g:"Данные", icon:"🧪", t:"ACID (свойства транзакций)",
  plain:"Гарантии надёжной транзакции: Атомарность (всё или ничего), Согласованность (данные остаются валидными), Изоляция (транзакции не мешают друг другу), Долговечность (записанное не пропадёт).",
  an:"Как нотариус сделки: либо оформили целиком и навсегда, либо не оформляли вовсе — без «полусделок».",
  en:{ t:"ACID (transaction properties)", plain:"Guarantees of a reliable transaction: Atomicity (all or nothing), Consistency (data stays valid), Isolation (transactions don't interfere), Durability (committed data won't vanish).", an:"Like a notary for a deal: either fully and permanently done, or not done at all — no 'half-deals'." } },
{ id:"b-replication", g:"Данные", icon:"👥", t:"Репликация",
  plain:"Держать копии данных на нескольких серверах. Если один упал — данные живы на других; плюс можно раздавать чтение с реплик, разгружая основную БД.",
  an:"Несколько копий важного документа в разных сейфах: сгорит один — остальные целы.",
  en:{ t:"Replication", plain:"Keep copies of data on several servers. If one dies, data survives on the others; plus you can serve reads from replicas, offloading the main DB.", an:"Several copies of an important document in different safes: one burns down — the rest are intact." } },
{ id:"b-nplus1", g:"Данные", icon:"🐌", t:"Проблема N+1 запросов",
  plain:"Взял список из N элементов одним запросом, а потом на каждый делаешь ещё запрос за деталями — итого N+1 походов в БД вместо одного-двух. Частый тихий тормоз в ORM.",
  an:"Купил список из 100 гостей, а потом звонишь каждому отдельно — 100 звонков вместо одной рассылки.",
  en:{ t:"N+1 query problem", plain:"You fetch a list of N items in one query, then make another query per item for details — N+1 DB round-trips instead of one or two. A common silent ORM slowdown.", an:"You get a list of 100 guests, then phone each one separately — 100 calls instead of one broadcast." } },
{ id:"b-idempotent", g:"Связь", icon:"♻️", t:"Идемпотентность",
  plain:"Операция даёт один и тот же результат, сколько раз её ни повтори. Важно при ретраях: если ответ потерялся и запрос повторили, деньги не спишутся дважды.",
  an:"Кнопка «этаж 5» в лифте: жми хоть десять раз — приедешь на пятый один раз, не на пятидесятый.",
  en:{ t:"Idempotency", plain:"An operation gives the same result no matter how many times you repeat it. Crucial for retries: if a response was lost and the request repeated, money isn't charged twice.", an:"The 'floor 5' button in a lift: press it ten times — you still arrive at the 5th once, not the 50th." } },
{ id:"b-timeout-retry", g:"Связь", icon:"⏱️", t:"Таймаут и повтор (retry)",
  plain:"Таймаут — предел ожидания ответа, чтобы не зависнуть навсегда на упавшем сервисе. Retry — повторить упавший запрос, но осторожно (с задержкой и только для идемпотентных операций).",
  an:"Ждёшь ответа на звонок минуту — не берут, кладёшь трубку (таймаут) и перезваниваешь позже (retry), а не висишь в тишине.",
  en:{ t:"Timeout and retry", plain:"A timeout is the limit on waiting for a response, so you don't hang forever on a dead service. Retry re-sends a failed request, but carefully (with a delay and only for idempotent operations).", an:"You wait a minute on a call — no answer, you hang up (timeout) and call back later (retry), instead of holding silence." } },
{ id:"b-webhook", g:"Связь", icon:"🪝", t:"Webhook",
  plain:"Обратный вызов: вместо того чтобы ты постоянно спрашивал «уже готово?», сервис сам шлёт тебе HTTP-запрос, когда событие произошло. Push вместо опроса.",
  an:"Не звонишь в пиццерию каждые 5 минут — они сами перезвонят, когда пицца готова.",
  en:{ t:"Webhook", plain:"A reverse call: instead of you constantly asking 'ready yet?', the service sends YOU an HTTP request when an event happens. Push instead of polling.", an:"You don't call the pizzeria every 5 minutes — they call you when the pizza is ready." } },
{ id:"b-sqli", g:"Веб · безопасность", icon:"💉", t:"SQL-инъекция",
  plain:"Атака, когда пользовательский ввод вклеивают прямо в SQL-запрос, и злоумышленник вписывает туда свою команду («'; DROP TABLE…»). Защита — параметризованные запросы (prepared statements), не склейка строк.",
  an:"Вписал в графу «имя» не имя, а приказ охране — и если бланк читают буквально, приказ выполнят.",
  en:{ t:"SQL injection", plain:"An attack where user input is pasted straight into a SQL query, and the attacker writes their own command there ('; DROP TABLE…'). Defense — parameterized queries (prepared statements), not string concatenation.", an:"Into the 'name' field you write not a name but an order to the guards — and if the form is read literally, the order gets carried out." } },
{ id:"b-xss", g:"Веб · безопасность", icon:"🕷️", t:"XSS (межсайтовый скриптинг)",
  plain:"Атака, когда чужой JavaScript попадает на страницу через непроверенный ввод и выполняется в браузере жертвы (крадёт куки, действует от её имени). Защита — экранировать вывод.",
  an:"Кто-то подсунул записку в стопку объявлений на доске, и все, кто читает, машинально выполняют написанное.",
  en:{ t:"XSS (cross-site scripting)", plain:"An attack where someone's JavaScript lands on a page via unsanitized input and runs in the victim's browser (steals cookies, acts as them). Defense — escape output.", an:"Someone slips a note into the stack of postings on a board, and everyone who reads it mechanically does what it says." } },
{ id:"b-pw-hash", g:"Веб · безопасность", icon:"🧂", t:"Хеширование паролей (соль)",
  plain:"Пароли нельзя хранить как есть — только их необратимый хеш (bcrypt/argon2). Соль — случайная добавка к каждому паролю, чтобы одинаковые пароли давали разные хеши и не ломались готовыми таблицами.",
  an:"Хранишь не ключ, а слепок замка; соль — уникальная зазубрина у каждого, чтобы одинаковые ключи не выглядели одинаково.",
  en:{ t:"Password hashing (salt)", plain:"Passwords must never be stored as-is — only their irreversible hash (bcrypt/argon2). A salt is a random addition to each password so identical passwords produce different hashes and can't be cracked by precomputed tables.", an:"You store not the key but an imprint of the lock; the salt is a unique notch on each, so identical keys don't look identical." } },
{ id:"b-unit-integ", g:"Инфраструктура", icon:"🧪", t:"Юнит- vs интеграционный тест",
  plain:"Юнит-тест проверяет один маленький кусок кода в изоляции (быстро, всё вокруг подменено). Интеграционный проверяет, что куски работают вместе — с реальной БД/сервисами (медленнее, но ближе к жизни).",
  an:"Юнит — проверить каждую деталь двигателя отдельно; интеграционный — завести собранную машину и проехать.",
  en:{ t:"Unit vs integration test", plain:"A unit test checks one small piece of code in isolation (fast, everything around is stubbed). An integration test checks that pieces work together — with a real DB/services (slower, but closer to reality).", an:"Unit — test each engine part separately; integration — start the assembled car and drive." } },
{ id:"b-mock", g:"Инфраструктура", icon:"🎬", t:"Мок (заглушка)",
  plain:"Поддельная замена реальной зависимости в тесте: возвращает заранее заданные ответы, чтобы проверить код в изоляции, не дёргая настоящую БД или чужой сервис.",
  an:"Манекен вместо живого пациента на тренировке: реакции заранее заданы, отрабатываешь свои действия безопасно.",
  en:{ t:"Mock (test double)", plain:"A fake stand-in for a real dependency in a test: it returns predefined answers so you can check code in isolation without touching a real DB or external service.", an:"A dummy instead of a live patient in training: reactions are preset, and you safely rehearse your actions." } },

{ id:"b-collections", g:"Код · Java", icon:"📚", t:"Коллекции: List, Set, Map",
  plain:"List — упорядоченный список с повторами (по индексу). Set — множество уникальных, без повторов. Map — пары ключ→значение (словарь). Выбор структуры определяет, что быстро, а что дорого.",
  an:"List — нумерованная очередь; Set — гостевой список без дублей; Map — телефонная книга «имя → номер».",
  en:{ t:"Collections: List, Set, Map", plain:"List — an ordered list allowing duplicates (by index). Set — a collection of unique items, no duplicates. Map — key→value pairs (a dictionary). The structure you pick decides what's fast and what's costly.", an:"List — a numbered queue; Set — a guest list with no duplicates; Map — a phone book 'name → number'." } },
{ id:"b-generics", g:"Код · Java", icon:"🔤", t:"Дженерики (generics)",
  plain:"Способ задать тип «внутри» контейнера: List<String> — список именно строк. Компилятор ловит ошибки типов заранее, и не нужно вручную приводить типы.",
  an:"Коробка с ярлыком «только книги»: не положишь туда обувь по ошибке, и доставая — точно знаешь, что там книга.",
  en:{ t:"Generics", plain:"A way to specify the type 'inside' a container: List<String> is a list of exactly strings. The compiler catches type errors ahead of time, and you don't cast manually.", an:"A box labeled 'books only': you won't put shoes in by mistake, and when you take something out you know it's a book." } },
{ id:"b-optional", g:"Код · Java", icon:"🎁", t:"Optional",
  plain:"Обёртка, которая явно говорит «значение может отсутствовать». Заставляет обработать случай «пусто» вместо внезапного NullPointerException.",
  an:"Коробка, которая честно подписана «может быть пустой»: ты заранее проверяешь, а не суёшь руку вслепую.",
  en:{ t:"Optional", plain:"A wrapper that explicitly says 'the value may be absent'. It forces you to handle the 'empty' case instead of a sudden NullPointerException.", an:"A box honestly labeled 'may be empty': you check first instead of reaching in blindly." } },
{ id:"b-lambda", g:"Код · Java", icon:"➡️", t:"Лямбда и функциональный интерфейс",
  plain:"Лямбда — короткая безымянная функция, которую можно передать как аргумент (напр. правило сортировки). Функциональный интерфейс — тип с одним методом, куда такая функция подставляется.",
  an:"Записка с инструкцией «сделай вот так», которую отдаёшь другому, чтобы он выполнил, — не заводя отдельный класс.",
  en:{ t:"Lambda and functional interface", plain:"A lambda is a short anonymous function you can pass as an argument (e.g. a sorting rule). A functional interface is a type with a single method where such a function plugs in.", an:"A note with an instruction 'do it like this' that you hand to someone to carry out — without setting up a whole class." } },
{ id:"b-enum", g:"Код · Java", icon:"🎚️", t:"Enum (перечисление)",
  plain:"Тип с фиксированным набором именованных значений (Status: NEW, PAID, SHIPPED). Компилятор не даст присвоить что-то вне списка — безопаснее строк и чисел-«магии».",
  an:"Переключатель передач: есть только P-R-N-D, нельзя воткнуть «передачу №7» — вариантов ровно столько, сколько разрешено.",
  en:{ t:"Enum", plain:"A type with a fixed set of named values (Status: NEW, PAID, SHIPPED). The compiler won't let you assign anything outside the list — safer than magic strings or numbers.", an:"A gear selector: only P-R-N-D exist, you can't shove in 'gear #7' — exactly as many options as allowed." } },
{ id:"b-orm", g:"Данные", icon:"🔗", t:"ORM",
  plain:"Слой, который отображает строки таблиц на объекты кода и обратно, чтобы не писать SQL вручную. Удобно, но скрывает запросы — легко получить лишние или тяжёлые (см. N+1).",
  an:"Переводчик между двумя языками — «таблицы БД» и «объекты кода»: говоришь на своём, он переводит на язык базы.",
  en:{ t:"ORM", plain:"A layer that maps table rows to code objects and back, so you don't write SQL by hand. Convenient, but it hides the queries — easy to end up with extra or heavy ones (see N+1).", an:"A translator between two languages — 'DB tables' and 'code objects': you speak yours, it translates to the database's." } },
{ id:"b-migration", g:"Данные", icon:"📜", t:"Миграции БД",
  plain:"Версионированные скрипты изменения схемы БД (добавить колонку, таблицу), которые применяются по порядку на всех окружениях. Так структура базы меняется контролируемо, а не руками.",
  an:"История правок документа под версиями: каждый может воспроизвести те же изменения в том же порядке и получить одинаковый итог.",
  en:{ t:"DB migrations", plain:"Versioned scripts that change the DB schema (add a column, a table), applied in order across all environments. So the database structure changes in a controlled way, not by hand.", an:"A versioned edit history of a document: anyone can replay the same changes in the same order and get the same result." } },
{ id:"b-dns", g:"Связь", icon:"📇", t:"DNS",
  plain:"Телефонная книга интернета: превращает человекочитаемое имя (example.com) в IP-адрес сервера. Браузер сначала спрашивает DNS, потом идёт по полученному адресу.",
  an:"Справочная: называешь имя фирмы — тебе дают её точный адрес, по которому и едешь.",
  en:{ t:"DNS", plain:"The internet's phone book: it turns a human-readable name (example.com) into a server's IP address. The browser asks DNS first, then goes to the address it gets.", an:"An information desk: you give a company's name, they give you its exact address, and off you go." } },
{ id:"b-port", g:"Связь", icon:"🚪", t:"Порт",
  plain:"Номер «двери» на сервере, за которой слушает конкретная программа. IP ведёт к машине, порт — к нужному приложению на ней (80/443 — веб, 5432 — Postgres).",
  an:"Адрес дома — это IP, а номер квартиры — порт: письмо доходит именно тому жильцу.",
  en:{ t:"Port", plain:"A 'door' number on a server behind which a specific program listens. The IP leads to the machine, the port to the right app on it (80/443 — web, 5432 — Postgres).", an:"The building address is the IP, the apartment number is the port: the letter reaches exactly that resident." } },
{ id:"b-cors", g:"Связь", icon:"🚧", t:"CORS",
  plain:"Правило браузера: страница с одного домена по умолчанию не может дёргать API другого домена. Сервер должен явно разрешить это заголовками — иначе браузер заблокирует запрос.",
  an:"Пропускной режим между зданиями: чтобы курьер с одного адреса вошёл в другое, там должны его в список пустить.",
  en:{ t:"CORS", plain:"A browser rule: a page from one domain can't call another domain's API by default. The server must explicitly allow it via headers — otherwise the browser blocks the request.", an:"An access policy between buildings: for a courier from one address to enter another, they must be on its allow-list." } },
{ id:"b-csrf", g:"Веб · безопасность", icon:"🎣", t:"CSRF",
  plain:"Атака, когда вредный сайт от твоего имени шлёт запрос на сайт, где ты уже залогинен (браузер сам приложит куки). Защита — CSRF-токен, который чужой сайт не знает.",
  an:"Кто-то подделал поручение от твоего имени в банк, зная, что там тебя узнают по подписи-куке. Секретный код-подтверждение ломает схему.",
  en:{ t:"CSRF", plain:"An attack where a malicious site sends a request in your name to a site you're already logged into (the browser attaches cookies itself). Defense — a CSRF token the foreign site doesn't know.", an:"Someone forges an order in your name to the bank, knowing it recognizes you by your cookie-signature. A secret confirmation code breaks the scheme." } },
{ id:"b-oauth", g:"Веб · безопасность", icon:"🎟️", t:"OAuth",
  plain:"Протокол «войти через Google/GitHub» без передачи пароля: сервис получает ограниченный токен-доступ от твоего имени, а пароль остаётся только у провайдера.",
  an:"Гостевой ключ от номера, который выдаёт ресепшн: пускает в нужные двери, но не даёт твой домашний ключ.",
  en:{ t:"OAuth", plain:"A 'log in with Google/GitHub' protocol without sharing your password: the service gets a limited access token on your behalf, while the password stays only with the provider.", an:"A guest key card issued by the front desk: it opens the right doors but never hands over your home key." } },
{ id:"b-env-config", g:"Инфраструктура", icon:"🎛️", t:"Переменные окружения / конфиг",
  plain:"Настройки (адреса БД, ключи, режимы), вынесенные наружу кода, а не зашитые в него. Так одно и то же приложение работает в dev/test/prod, меняя лишь конфиг, а секреты не лежат в коде.",
  an:"Одна и та же кофемашина: рецепт-код общий, а вода и зёрна (настройки) подставляются на месте под каждое кафе.",
  en:{ t:"Environment variables / config", plain:"Settings (DB addresses, keys, modes) kept outside the code, not hardcoded. So the same app runs in dev/test/prod by changing only config, and secrets don't live in the code.", an:"The same coffee machine: the recipe-code is shared, but water and beans (settings) are supplied on site per café." } },
{ id:"b-feature-flag", g:"Инфраструктура", icon:"🚩", t:"Feature flag",
  plain:"Переключатель, включающий/выключающий фичу без перевыката кода. Позволяет катить незаконченное скрытым, включать для части пользователей и быстро гасить проблемную фичу.",
  an:"Рубильник для отдельной витрины в магазине: товар уже завезли, но включишь свет над ним, когда решишь — и погасишь, если что.",
  en:{ t:"Feature flag", plain:"A switch that turns a feature on/off without redeploying code. Lets you ship unfinished work hidden, enable it for a subset of users, and kill a problematic feature fast.", an:"A switch for one store display: the goods are already delivered, but you turn the light on when you decide — and off if something's wrong." } },
{ id:"b-ram-disk", g:"Инфраструктура", icon:"💾", t:"Оперативка (RAM) vs диск",
  plain:"RAM — быстрая, но временная память (исчезает при выключении); диск — медленнее, зато хранит данные постоянно. Программы работают в RAM, а важное сохраняют на диск.",
  an:"RAM — стол, на котором работаешь прямо сейчас (быстро, но на ночь убирают); диск — шкаф, где всё лежит и не пропадает.",
  en:{ t:"RAM vs disk", plain:"RAM is fast but temporary memory (gone when powered off); disk is slower but stores data permanently. Programs work in RAM and save what matters to disk.", an:"RAM — the desk you work on right now (fast, but cleared overnight); disk — the cabinet where everything is kept and doesn't vanish." } },

{ id:"b-recursion", g:"Код · Java", icon:"🪆", t:"Рекурсия",
  plain:"Функция вызывает саму себя на задаче поменьше, пока не дойдёт до простого случая (базы), на котором останавливается. Удобно для вложенных структур: папки, деревья.",
  an:"Матрёшки: открываешь одну — внутри такая же поменьше, и так до самой маленькой, которая уже не открывается.",
  en:{ t:"Recursion", plain:"A function calls itself on a smaller task until it reaches a simple base case where it stops. Handy for nested structures: folders, trees.", an:"Nesting dolls: open one — inside is a smaller same one, and so on to the tiniest that no longer opens." } },
{ id:"b-constructor", g:"Код · Java", icon:"🏗️", t:"Конструктор",
  plain:"Особый метод, который вызывается при создании объекта и задаёт его начальное состояние (заполняет поля). Гарантирует, что объект рождается «готовым к работе».",
  an:"Сборка на конвейере при выпуске: машина сходит с линии уже с колёсами и мотором, а не пустым корпусом.",
  en:{ t:"Constructor", plain:"A special method called when an object is created that sets its initial state (fills the fields). It guarantees the object is born 'ready to use'.", an:"Assembly on the line at manufacture: the car rolls off already with wheels and an engine, not an empty shell." } },
{ id:"b-try-catch", g:"Код · Java", icon:"🧯", t:"Обработка ошибок (try/catch)",
  plain:"try — «попробуй выполнить рискованный код», catch — «а если упадёт с ошибкой, вот что делать». Так программа не рушится целиком, а корректно реагирует на сбой.",
  an:"Страховочная сетка у акробата: сорвался — не разбился, сетка ловит и позволяет продолжить представление.",
  en:{ t:"Error handling (try/catch)", plain:"try — 'attempt the risky code', catch — 'and if it fails with an error, here's what to do'. So the program doesn't crash entirely but responds to failure gracefully.", an:"A safety net under an acrobat: if they fall, they aren't hurt — the net catches them and the show goes on." } },
{ id:"b-cast", g:"Код · Java", icon:"🔁", t:"Приведение типов (cast)",
  plain:"Указание компилятору трактовать значение как другой тип. Расширение (int→long) безопасно; сужение (double→int, Object→String) может потерять данные или упасть, если тип на деле не тот.",
  an:"Переклеить ярлык на коробке: с «книги» на «предмет» — ок; обратно на «книгу» — только если внутри правда книга, иначе конфуз.",
  en:{ t:"Type casting", plain:"Telling the compiler to treat a value as another type. Widening (int→long) is safe; narrowing (double→int, Object→String) may lose data or fail if the type isn't really that.", an:"Relabeling a box: from 'book' to 'item' — fine; back to 'book' — only if there's really a book inside, else trouble." } },
{ id:"b-conn-pool", g:"Данные", icon:"🔌", t:"Пул соединений (connection pool)",
  plain:"Набор заранее открытых соединений с БД, которые переиспользуются. Открывать соединение каждый раз дорого и медленно, поэтому их держат наготове и выдают по запросу.",
  an:"Прокат велосипедов у вокзала: не покупаешь свой на каждую поездку — берёшь из стойки готовый и возвращаешь.",
  en:{ t:"Connection pool", plain:"A set of pre-opened DB connections that get reused. Opening a connection each time is costly and slow, so they're kept ready and handed out on demand.", an:"A bike-share rack at the station: you don't buy your own for each trip — you grab a ready one and return it." } },
{ id:"b-partition", g:"Данные", icon:"🍕", t:"Партиционирование",
  plain:"Разбиение одной огромной таблицы на части (по дате, региону), чтобы запросы работали с нужным куском, а не со всем объёмом. Ускоряет и упрощает обслуживание больших данных.",
  an:"Толстую энциклопедию делят на тома: ищешь на букву «М» — берёшь один том, а не ворочаешь всю махину.",
  en:{ t:"Partitioning", plain:"Splitting one huge table into parts (by date, region) so queries work on the relevant slice, not the whole volume. Speeds up and simplifies maintenance of big data.", an:"A fat encyclopedia is split into volumes: looking under 'M' — you take one volume, not heave the whole thing." } },
{ id:"b-websocket", g:"Связь", icon:"🔊", t:"WebSocket",
  plain:"Постоянное двустороннее соединение между браузером и сервером: обе стороны могут слать сообщения в любой момент, не переспрашивая. Для чатов, уведомлений, live-обновлений.",
  an:"Открытая телефонная линия вместо писем: говорите оба в любой момент, не вешая трубку после каждой фразы.",
  en:{ t:"WebSocket", plain:"A persistent two-way connection between browser and server: both sides can send messages anytime without re-asking. For chats, notifications, live updates.", an:"An open phone line instead of letters: both talk anytime, without hanging up after each sentence." } },
{ id:"b-grpc", g:"Связь", icon:"⚡", t:"gRPC",
  plain:"Способ вызова методов чужого сервиса как своих (RPC) поверх HTTP/2 с компактным бинарным форматом (protobuf). Быстрее и строже по контракту, чем REST/JSON — часто между микросервисами.",
  an:"Прямой служебный телефон между отделами со строгим бланком заявки — быстрее и без разночтений, чем письма на общем языке.",
  en:{ t:"gRPC", plain:"A way to call another service's methods as if your own (RPC) over HTTP/2 with a compact binary format (protobuf). Faster and stricter on contract than REST/JSON — often between microservices.", an:"A direct internal phone between departments with a strict request form — faster and less ambiguous than letters in plain language." } },
{ id:"b-reverse-proxy", g:"Связь", icon:"🛡️", t:"Reverse proxy",
  plain:"Сервер-«секретарь» перед твоими приложениями: принимает все внешние запросы и распределяет их внутрь, попутно занимаясь TLS, кэшем, лимитами. Клиент не видит, что стоит за ним.",
  an:"Ресепшн бизнес-центра: посетители обращаются туда, а он уже направляет к нужному кабинету — сами кабинеты снаружи не видны.",
  en:{ t:"Reverse proxy", plain:"A 'receptionist' server in front of your apps: it takes all external requests and routes them inward, handling TLS, caching, limits along the way. The client doesn't see what's behind it.", an:"A business-center front desk: visitors go there, and it directs them to the right office — the offices themselves aren't visible from outside." } },
{ id:"b-refresh-token", g:"Веб · безопасность", icon:"🔄", t:"Refresh token",
  plain:"Короткоживущий access-токен даёт доступ, но быстро протухает ради безопасности. Долгоживущий refresh-токен позволяет тихо получить новый access, не заставляя логиниться заново.",
  an:"Бумажный талон на день (access) и абонемент на месяц (refresh): талон обновляешь по абонементу, не покупая заново весь пакет.",
  en:{ t:"Refresh token", plain:"A short-lived access token grants access but expires quickly for safety. A long-lived refresh token lets you silently get a new access token without logging in again.", an:"A day pass (access) and a monthly membership (refresh): you renew the pass via the membership, not re-buying the whole package." } },
{ id:"b-2fa", g:"Веб · безопасность", icon:"🔐", t:"Двухфакторная аутентификация (2FA)",
  plain:"Вход подтверждается двумя разными факторами: что ты знаешь (пароль) + что у тебя есть (код из приложения/SMS). Украли пароль — без второго фактора всё равно не войдут.",
  an:"Дверь с двумя замками под разные ключи: подобрали один — второй всё равно держит.",
  en:{ t:"Two-factor authentication (2FA)", plain:"Login is confirmed by two different factors: something you know (password) + something you have (a code from an app/SMS). Even if the password is stolen, they can't get in without the second factor.", an:"A door with two locks needing different keys: pick one — the other still holds." } },
{ id:"b-log-levels", g:"Инфраструктура", icon:"🎚️", t:"Уровни логов",
  plain:"Логи делят по важности: DEBUG (подробности для отладки), INFO (обычные события), WARN (подозрительно, но живём), ERROR (сломалось). В проде оставляют INFO+ и повышают детализацию при разборе.",
  an:"Громкость сообщений: шёпот-детали (DEBUG) для своих, обычная речь (INFO), тревожный тон (WARN) и крик (ERROR), когда пожар.",
  en:{ t:"Log levels", plain:"Logs are ranked by importance: DEBUG (debugging detail), INFO (normal events), WARN (suspicious but ok), ERROR (broken). In prod you keep INFO+ and raise verbosity when investigating.", an:"Message volume: whispered details (DEBUG) for insiders, normal speech (INFO), an alarmed tone (WARN), and a shout (ERROR) when there's a fire." } }
];
