/* Фразы для собеседования по-английски.
 *
 * Не «английский вообще», а то, что говорят на техническом собесе: уточнить
 * вопрос, думать вслух, назвать компромисс, не согласиться, взять паузу.
 * Каждая фраза — готовый оборот, который можно произнести целиком; ru — что она
 * значит, note — когда её говорить и на что обратить внимание.
 *
 * Схема: [{id, ico, group, when, items:[{en, ru, note?}]}]
 */
window.ENGPHRASES = [

{ id:"intro", ico:"👋", group:"Представиться", when:"Первые две минуты. Коротко: кто ты, что делаешь сейчас, почему здесь.",
  items:[
  { en:"I'm a backend engineer with about six years of experience, mostly in Java and Spring.",
    ru:"Я бэкенд-разработчик с опытом около шести лет, в основном Java и Spring.",
    note:"Число лет и стек — в первом же предложении. Дальше слушают уже с картинкой." },
  { en:"Currently I work at a bank, on the brokerage platform — order processing and document generation.",
    ru:"Сейчас работаю в банке, на брокерской платформе — обработка ордеров и генерация документов.",
    note:"«Currently» + компания + продукт + две области. Без перечисления всех сервисов." },
  { en:"My day-to-day is mostly designing services, reviewing code and dealing with production issues.",
    ru:"По будням в основном проектирую сервисы, смотрю код и разбираюсь с прод-инцидентами.",
    note:"«Day-to-day» — естественный оборот про рутину, звучит живо." },
  { en:"The project I'm most proud of is migrating a legacy monolith to hexagonal services.",
    ru:"Проект, которым горжусь больше всего, — перевод легаси-монолита на гексагональные сервисы." },
  { en:"I'm looking for a role where I can own a system end to end, not just a slice of it.",
    ru:"Ищу роль, где отвечаешь за систему целиком, а не за её кусок.",
    note:"Ответ на «почему уходите» без негатива о текущем месте." },
  { en:"Outside of work I keep a personal trading bot running — it's my sandbox for trying things out.",
    ru:"Вне работы у меня крутится личный торговый бот — это моя песочница для экспериментов.",
    note:"Один личный проект — достаточно. Показывает, что тебе интересно, а не что ты перегружен." },
  { en:"Happy to go deeper into any of that.",
    ru:"С радостью расскажу подробнее о любом из этого.",
    note:"Закрывает представление и передаёт ход. Без этого возникает неловкая пауза." },
  { en:"Before I start — how much time do we have, and what would you like to focus on?",
    ru:"Прежде чем начать — сколько у нас времени и на чём вы хотели бы сосредоточиться?",
    note:"Задаёт рамку и показывает, что ты умеешь управлять разговором." }
]},

{ id:"clarify", ico:"🔍", group:"Уточнить вопрос", when:"Перед тем как отвечать. Уточнение — не слабость, а первое, что ждут от сеньора.",
  items:[
  { en:"Just to make sure I understand — are you asking about X or about Y?",
    ru:"Чтобы убедиться, что понял правильно, — вы спрашиваете про X или про Y?" },
  { en:"Could you clarify what you mean by \"scalable\" here — throughput, data volume, or team size?",
    ru:"Уточните, что вы имеете в виду под «масштабируемый» — пропускную способность, объём данных или размер команды?",
    note:"Расплывчатое слово в вопросе — всегда повод спросить. Три варианта показывают, что ты видишь все три измерения." },
  { en:"What scale are we talking about — thousands of users or millions?",
    ru:"О каком масштабе речь — тысячи пользователей или миллионы?" },
  { en:"Is this a read-heavy or a write-heavy workload?",
    ru:"Это нагрузка с преобладанием чтения или записи?" },
  { en:"Are there any constraints I should know about — latency, budget, existing infrastructure?",
    ru:"Есть ли ограничения, о которых мне стоит знать — задержка, бюджет, существующая инфраструктура?" },
  { en:"Can I assume the data fits on a single machine, or should I design for sharding from the start?",
    ru:"Могу ли я считать, что данные помещаются на одну машину, или закладывать шардирование сразу?" },
  { en:"How strict is consistency here — does a few seconds of staleness matter?",
    ru:"Насколько строга согласованность — важны ли несколько секунд устаревания?" },
  { en:"Let me restate the problem in my own words so we're on the same page.",
    ru:"Давайте я перескажу задачу своими словами, чтобы мы были на одной волне.",
    note:"«On the same page» — идиома именно для этого. Пересказ ловит недопонимание до того, как ты потратишь десять минут." },
  { en:"Do you want me to go broad and cover the whole system, or go deep on one component?",
    ru:"Вы хотите, чтобы я прошёлся широко по всей системе или углубился в один компонент?" },
  { en:"Is it okay if I skip authentication for now and come back to it if we have time?",
    ru:"Ничего, если я пока пропущу аутентификацию и вернусь к ней, если останется время?",
    note:"Честно отложить второстепенное лучше, чем размазать время по всему." }
]},

{ id:"think", ico:"🧠", group:"Думать вслух", when:"Молчание на собесе — худшее. Проговаривай ход мысли, даже если он пока не ведёт к ответу.",
  items:[
  { en:"Let me think out loud for a second.",
    ru:"Дайте секунду подумать вслух.",
    note:"Самая полезная фраза раздела. Даёт право на паузу и объясняет, что дальше будет черновик." },
  { en:"My first instinct is to use a queue here, but let me check that against the requirements.",
    ru:"Первое, что приходит в голову, — очередь, но давайте сверю это с требованиями.",
    note:"«First instinct» + «let me check» — показывает, что ты не хватаешься за первое решение." },
  { en:"There are two ways I can see to approach this.",
    ru:"Я вижу два способа подойти к этому." },
  { en:"The naive approach would be to… but that breaks down when…",
    ru:"Наивный подход — это… но он ломается, когда…",
    note:"Назвать наивное решение и его предел — сильнее, чем сразу выдать правильное." },
  { en:"Let me do some rough numbers first.",
    ru:"Давайте сначала прикину числа.",
    note:"«Rough numbers» / «back-of-the-envelope» — оценка нагрузки, второй этап любого дизайна." },
  { en:"So that's roughly four thousand requests per second — that's manageable for a single database.",
    ru:"Итого примерно четыре тысячи запросов в секунду — одна база с этим справится." },
  { en:"Hold on, I think I'm overcomplicating this.",
    ru:"Погодите, кажется, я усложняю.",
    note:"Поймать себя на переусложнении вслух — это плюс, а не минус." },
  { en:"Actually, let me step back — what problem are we really solving here?",
    ru:"Вообще-то, давайте отступлю на шаг — какую задачу мы на самом деле решаем?" },
  { en:"The key question is where the bottleneck will be.",
    ru:"Ключевой вопрос — где окажется узкое место." },
  { en:"I'd start simple and add complexity only where the numbers demand it.",
    ru:"Я бы начал с простого и добавлял сложность только там, где этого требуют числа." },
  { en:"Let me sketch this out.",
    ru:"Давайте набросаю схему.",
    note:"Перед тем как рисовать. Даже на созвоне — словами: «On the left we have…»." },
  { en:"That covers the happy path. Now, what happens when things go wrong?",
    ru:"Это основной сценарий. Теперь — что происходит, когда что-то идёт не так?",
    note:"«Happy path» — стандартный термин. Переход к отказам сам, без подсказки — признак сеньора." }
]},

{ id:"tradeoff", ico:"⚖️", group:"Компромисс и решение", when:"Любое решение имеет цену. Назвать её вслух — то, за что ставят плюс.",
  items:[
  { en:"There's a trade-off here between consistency and availability.",
    ru:"Здесь компромисс между согласованностью и доступностью." },
  { en:"The upside is simplicity; the downside is that we lose exactly-once delivery.",
    ru:"Плюс — простота, минус — теряем доставку ровно один раз.",
    note:"«Upside / downside» — компактная пара для любого решения." },
  { en:"We're trading accuracy for throughput, and for view counts that's an acceptable trade.",
    ru:"Мы меняем точность на пропускную способность, и для счётчика просмотров это приемлемая сделка." },
  { en:"I'd go with option A because it's easier to operate, even though B is faster on paper.",
    ru:"Я бы выбрал вариант A, потому что его проще эксплуатировать, хотя B на бумаге быстрее.",
    note:"«Even though» — признаёшь сильную сторону отвергнутого варианта. Это честность, её замечают." },
  { en:"The price we pay for the cache is that the database can no longer survive without it.",
    ru:"Цена кэша в том, что база без него больше не выживает." },
  { en:"This is the decision that's hard to reverse, so I'd spend more time on it.",
    ru:"Это решение, которое трудно откатить, поэтому на него я бы потратил больше времени.",
    note:"Отличать обратимое от необратимого — сеньорный признак. Ключ шардирования, схема событий." },
  { en:"It depends — and here's what it depends on.",
    ru:"Зависит — и вот от чего именно.",
    note:"«It depends» без продолжения — отговорка. С продолжением — лучший ответ." },
  { en:"If I had to pick one, I'd pick the outbox pattern.",
    ru:"Если выбирать что-то одно, я бы взял outbox.",
    note:"Когда просят определиться. Не «both are fine»." },
  { en:"That would work, but it adds a second source of truth, and I'd rather avoid that.",
    ru:"Это сработает, но добавляет второй источник правды, а я бы этого избегал." },
  { en:"I'm deliberately not using a distributed transaction here — the operational cost isn't worth it.",
    ru:"Я намеренно не использую здесь распределённую транзакцию — эксплуатационная цена того не стоит." },
  { en:"Good enough for now; we can revisit once we see real traffic.",
    ru:"Пока достаточно; вернёмся к этому, когда увидим реальный трафик." }
]},

{ id:"disagree", ico:"🙅", group:"Не согласиться вежливо", when:"Собеседник может проверять, прогнёшься ли. Спорить по делу — можно и нужно, тон — мягкий.",
  items:[
  { en:"I see your point, but I'd push back a little on that.",
    ru:"Понимаю вашу мысль, но немного возражу.",
    note:"«Push back» — стандартный мягкий глагол для несогласия. Не «you're wrong»." },
  { en:"I'm not sure that holds under high load — let me explain why.",
    ru:"Не уверен, что это выдержит высокую нагрузку — объясню почему." },
  { en:"That's true in general, but in this case I think the numbers say otherwise.",
    ru:"В целом это верно, но здесь, мне кажется, цифры говорят другое." },
  { en:"I'd challenge the assumption that we need real-time here.",
    ru:"Я бы поставил под сомнение допущение, что здесь нужен реальный масштаб времени." },
  { en:"Fair point. Let me reconsider.",
    ru:"Справедливо. Дайте пересмотрю.",
    note:"Когда собеседник прав. Признать быстро — сильнее, чем отбиваться." },
  { en:"You're right, I missed that. So that changes the design to…",
    ru:"Вы правы, я это упустил. Значит, дизайн меняется на…" },
  { en:"I'd respectfully disagree — in my experience that approach leads to…",
    ru:"При всём уважении не соглашусь — по моему опыту такой подход приводит к…" },
  { en:"Can I offer a different angle on this?",
    ru:"Можно предложить другой угол зрения?" },
  { en:"I think we're solving different problems — let me check which one you mean.",
    ru:"Кажется, мы решаем разные задачи — уточню, какую вы имеете в виду." }
]},

{ id:"pause", ico:"⏸", group:"Взять паузу и «не знаю»", when:"Не знать — нормально. Плохо — молчать, врать или растекаться.",
  items:[
  { en:"Give me a moment to gather my thoughts.",
    ru:"Дайте минуту собраться с мыслями." },
  { en:"That's a good question — I haven't run into that exact case.",
    ru:"Хороший вопрос — с таким конкретным случаем я не сталкивался.",
    note:"Честно, и сразу продолжай: «but here's how I'd reason about it»." },
  { en:"I don't know off the top of my head, but here's how I'd find out.",
    ru:"Навскидку не скажу, но вот как я бы это выяснил.",
    note:"«Off the top of my head» — идиома для «навскидку». Дальше — способ, а не извинения." },
  { en:"I'm not certain, but my understanding is that…",
    ru:"Не уверен, но насколько я понимаю…" },
  { en:"Let me reason about it from first principles.",
    ru:"Давайте порассуждаю от базовых принципов.",
    note:"Когда не помнишь факт, но можешь его вывести. Собеседник любит именно это." },
  { en:"I'd have to check the docs to be sure, but I believe the default is…",
    ru:"Надо бы свериться с документацией, но, кажется, по умолчанию там…" },
  { en:"Can I come back to this one? I'd like to think about it a bit more.",
    ru:"Можно вернуться к этому позже? Хочу подумать чуть больше." },
  { en:"Honestly, I've only used it once, so take this with a grain of salt.",
    ru:"Честно говоря, я пользовался этим один раз, так что отнеситесь с осторожностью.",
    note:"«With a grain of salt» — идиома, снимает претензии на экспертизу без потери лица." },
  { en:"I'm going to guess, and tell you that it's a guess.",
    ru:"Я предположу — и скажу, что это предположение." },
  { en:"Could you give me a hint on the direction? I want to make sure I'm not going down a rabbit hole.",
    ru:"Подскажете направление? Не хочу уйти в кроличью нору.",
    note:"«Rabbit hole» — уйти в бесполезную глубину. Попросить подсказку — не стыдно, застрять — хуже." }
]},

{ id:"experience", ico:"💼", group:"Про опыт и проект", when:"Рассказ о проекте: ситуация → что сделал → результат числом. Без «мы», где было «я».",
  items:[
  { en:"The situation was: the service took forty seconds to generate a report, and clients were timing out.",
    ru:"Ситуация была такая: сервис генерировал отчёт сорок секунд, и клиенты отваливались по таймауту.",
    note:"Начать с проблемы и числа. Без предыстории компании." },
  { en:"I was the one who proposed moving the generation to a background job with an outbox.",
    ru:"Именно я предложил вынести генерацию в фоновую задачу с outbox.",
    note:"«I was the one who» — твой личный вклад, а не команды." },
  { en:"We cut the response time from forty seconds to under two.",
    ru:"Мы сократили время ответа с сорока секунд до менее чем двух.",
    note:"Результат — числом. «Improved performance» ничего не говорит." },
  { en:"The hardest part wasn't the code, it was getting the legacy team to agree on the boundaries.",
    ru:"Самым сложным был не код, а договориться с легаси-командой о границах." },
  { en:"In hindsight, I'd have introduced the feature flag earlier.",
    ru:"Оглядываясь назад, я бы ввёл фича-флаг раньше.",
    note:"«In hindsight» — про то, что сделал бы иначе. Вопрос про ошибки задают всегда." },
  { en:"I owned that service end to end — from design to on-call.",
    ru:"Я отвечал за этот сервис целиком — от дизайна до дежурств." },
  { en:"We had a production incident where the outbox reader silently stopped, and I was the one who found it.",
    ru:"У нас был прод-инцидент: читатель outbox молча остановился, и нашёл это я." },
  { en:"What I learned from that is to always alert on the absence of events, not just on errors.",
    ru:"Из этого я вынес: тревога нужна и на отсутствие событий, а не только на ошибки." },
  { en:"I mentored two junior engineers on that team.",
    ru:"Я менторил двух джуниоров в той команде." },
  { en:"It shipped in three months, on time, with zero rollbacks.",
    ru:"Выкатили за три месяца, в срок, без единого отката." },
  { en:"I'd rather not go into the details of that — it's under NDA — but the shape of the problem was…",
    ru:"Не буду вдаваться в детали — это под NDA, — но суть задачи была в…",
    note:"Про банк спросят. Отказать в деталях и дать форму задачи — нормально и ожидаемо." }
]},

{ id:"ask", ico:"❓", group:"Вопросы им", when:"В конце всегда спросят «any questions?». «No» — худший ответ. Два-три вопроса про работу, не про отпуск.",
  items:[
  { en:"What does a typical week look like for someone in this role?",
    ru:"Как выглядит обычная неделя человека на этой роли?" },
  { en:"How do you handle on-call, and how often does it actually fire?",
    ru:"Как устроены дежурства и как часто они реально срабатывают?" },
  { en:"What's the biggest technical challenge the team is facing right now?",
    ru:"Какая самая большая техническая проблема у команды прямо сейчас?" },
  { en:"How do decisions get made when engineers disagree?",
    ru:"Как принимаются решения, когда инженеры не согласны друг с другом?" },
  { en:"What would you expect me to have shipped in the first three months?",
    ru:"Что, по-вашему, я должен выкатить за первые три месяца?",
    note:"Показывает, что ты думаешь о результате, и даёт понять их ожидания." },
  { en:"How much of the codebase is legacy, and is there a plan for it?",
    ru:"Какая часть кодовой базы — легаси, и есть ли план на неё?" },
  { en:"What's the ratio of building new things to maintaining existing ones?",
    ru:"Каково соотношение нового и поддержки существующего?" },
  { en:"Is there anything about my background that gives you pause?",
    ru:"Есть ли что-то в моём опыте, что вызывает у вас сомнения?",
    note:"Смелый вопрос. Даёт шанс закрыть возражение на месте, а не узнать о нём из отказа." },
  { en:"What are the next steps in the process?",
    ru:"Какие следующие шаги в процессе?" }
]},

{ id:"wrap", ico:"🏁", group:"Закончить", when:"Последние тридцать секунд запоминаются лучше всего.",
  items:[
  { en:"To sum up: I'd go with the outbox, keep the consumer idempotent, and defer sharding until the numbers demand it.",
    ru:"Подытоживая: я бы взял outbox, сделал потребителя идемпотентным и отложил шардирование, пока числа не потребуют.",
    note:"Итог в одно предложение. Собеседник запишет именно его." },
  { en:"If I had more time, I'd look into the failure modes of the fallback channel.",
    ru:"Будь у меня больше времени, я бы разобрал сценарии отказа запасного канала.",
    note:"Назвать, что не успел, — лучше, чем надеяться, что не заметят." },
  { en:"Thanks, this was a genuinely interesting problem.",
    ru:"Спасибо, это была по-настоящему интересная задача." },
  { en:"I enjoyed the conversation — I hope to hear from you.",
    ru:"Мне понравился разговор — надеюсь на ответ от вас." },
  { en:"Is there anything I should prepare for the next round?",
    ru:"Стоит ли мне что-то подготовить к следующему этапу?" }
]}

];
