/* Кадры к 45 новым карточкам. Дописываются в window.PICS из pics.js. */
Object.assign(window.PICS||(window.PICS={}), {
 "njava-core": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box acc big\">record Trade(<br>String id, long sum)</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good\">private final &times;2<br>канонический ctor<br>id() sum()<br>equals/hashCode/toString</div></div><div class=\"fp-row\"><span class=\"fp-tag\">неявно final, уже наследует java.lang.Record</span><div class=\"fp-box bad fp-pulse-r\">extends Base<br>своё поле cache<br>&mdash; нельзя</div><div class=\"fp-arrow\">&hArr;</div><div class=\"fp-box good\">implements Comparable<br>&mdash; можно</div></div><div class=\"fp-row\"><span class=\"fp-tag\">валидация и копия</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good\">Trade { if (sum &lt; 0) throw ... }<br>компактный конструктор</div></div></div>",
  "cap": "record Trade: 4 члена генерит компилятор; extends и своё поле — нет, интерфейс — да"
 },
 "njava-boxing": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box\">в коде<br>int c = map.get(\"k\")</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box acc\">javac дописал<br>.intValue()</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-pulse-r\">ключа нет &rarr; null<br>null.intValue() = NPE</div></div><div class=\"fp-row\"><span class=\"fp-tag\">вызова в исходнике нет, а стектрейс тычет в строку присваивания</span></div><div class=\"fp-row\"><div class=\"fp-box good\">Integer c = map.get(\"k\")<br>null доехал живым</div><div class=\"fp-arrow\">&hArr;</div><div class=\"fp-box bad fp-blink\">flag ? 1 : nullInteger<br>тип выражения int &rarr; NPE</div></div></div>",
  "cap": "int c = map.get(k): javac дописал .intValue(), null → NPE на строке присваивания"
 },
 "njava-core-2": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box big\">LocalDateTime<br>2026-08-14T10:00</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box mut\">смещения внутри нет:<br>10:00 «где-то»</div></div><div class=\"fp-row\"><div class=\"fp-box acc\">ноут TZ=Asia/Almaty<br>= 05:00Z</div><div class=\"fp-arrow\">&hArr;</div><div class=\"fp-box bad fp-pulse-r\">контейнер TZ=UTC<br>= 10:00Z</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-val\">5 ч</div></div><div class=\"fp-row\"><span class=\"fp-tag\">момент времени</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good\">Instant / timestamptz</div><div class=\"fp-box good\">ZonedDateTime<br>только на экране</div></div></div>",
  "cap": "10:00 без зоны: на ноуте это 05:00Z, в UTC-контейнере 10:00Z — отчёт уехал на 5 ч"
 },
 "njava-generics": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">массив</span><div class=\"fp-box\">Object[] a = new String[3]</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box\">a[0] = 42</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-pulse-r\">рантайм:<br>ArrayStoreException</div></div><div class=\"fp-row\"><span class=\"fp-tag\">дженерик</span><div class=\"fp-box\">List&lt;Object&gt; l = strings</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good fp-pulse-g\">javac: incompatible types<br>до прода не доедет</div></div><div class=\"fp-row\"><div class=\"fp-box acc\">у String[] тип элемента<br>жив в рантайме &rarr; aastore</div><div class=\"fp-arrow\">&hArr;</div><div class=\"fp-box mut\">у List&lt;String&gt; стёрт &mdash;<br>сверять не с чем</div></div></div>",
  "cap": "a[0]=42 компилируется и падает ArrayStoreException; List<Object>=List<String> не собран"
 },
 "njava-numbers": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box acc big\">2147483647</div><div class=\"fp-token\">+ 1</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad big fp-pulse-r\">&minus;2147483648</div><span class=\"fp-tag\">молча, по кругу</span></div><div class=\"fp-row\"><div class=\"fp-box\">low = 2^30<br>high = 2^31&minus;1</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad\">(low + high) / 2<br>= &minus;536870912</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-blink\">arr[mid]<br>AIOOBE</div></div><div class=\"fp-row\"><div class=\"fp-box good fp-pulse-g\">low + (high &minus; low) / 2<br>или (low + high) &gt;&gt;&gt; 1</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good\">addExact &rarr;<br>ArithmeticException</div></div></div>",
  "cap": "low=2^30, high=2^31−1: (low+high)/2 = −536870912 → индекс отрицательный"
 },
 "njava-strings": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box\">\"a.b.c\".split(\".\")</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-pulse-r\">«.» = любой символ<br>все куски пустые</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-val\">0</div></div><div class=\"fp-row\"><div class=\"fp-box\">\"a,b,,\".split(\",\")</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-cell on\"></div><div class=\"fp-cell on\"></div><div class=\"fp-cell dead\"></div><div class=\"fp-cell dead\"></div><span class=\"fp-tag\">хвостовые пустые срезаны</span><div class=\"fp-val\">2</div></div><div class=\"fp-row\"><div class=\"fp-box good\">split(\",\", -1)</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-cell on\"></div><div class=\"fp-cell on\"></div><div class=\"fp-cell on\"></div><div class=\"fp-cell on\"></div><div class=\"fp-val\">4</div></div><div class=\"fp-row\"><span class=\"fp-tag\">литеральная точка</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good\">Pattern.quote(\".\")<br>или \"\\\\.\"</div><div class=\"fp-box good\">replace() &mdash; без regex</div></div></div>",
  "cap": "split(\".\") → 0 элементов; \"a,b,,\".split(\",\") → 2, а с limit −1 → 4"
 },
 "njava-arrays": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box acc\">a = {x, y}<br>@6d06d69c</div><div class=\"fp-token\">a.equals(b)</div><div class=\"fp-box acc\">b = {x, y}<br>@7a81197d</div></div><div class=\"fp-row\"><span class=\"fp-tag\">Object.equals — по ссылке</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-pulse-r\">false</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good\">Arrays.equals<br>true</div></div><div class=\"fp-row\"><span class=\"fp-tag\">println(a)</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad\">[Ljava.lang.String;<br>@6d06d69c</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good\">Arrays.toString<br>[x, y]</div></div></div>",
  "cap": "Содержимое одно, ссылки разные: equals=false, Arrays.equals=true, println даёт тип@хэш"
 },
 "njava-equals-hashcod": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box acc\">Point<br>o instanceof Point</div><div class=\"fp-arrow\">&#8644;</div><div class=\"fp-box\">ColorPoint<br>+ color</div></div><div class=\"fp-row\"><span class=\"fp-tag\">p.equals(cp)</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good\">true</div><span class=\"fp-tag\">cp.equals(p)</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-pulse-r\">false</div></div><div class=\"fp-row\"><div class=\"fp-slot\">indexOf зовёт equals аргумента</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-blink\">list.remove(cp) = false,<br>элемент на месте</div></div></div>",
  "cap": "p.equals(cp)=true, cp.equals(p)=false — remove/contains находят объект в одну сторону"
 },
 "nsyst-ekspluataciya": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box mut\">под v1<br>SELECT client_name</div><div class=\"fp-box acc\">под v2<br>SELECT full_name</div><span class=\"fp-tag\">оба в Endpoints</span></div><div class=\"fp-row\"><div class=\"fp-token\">ALTER … RENAME</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-pulse-r\">column client_name<br>does not exist</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad\">500 на половине<br>трафика</div></div><div class=\"fp-row\"><span class=\"fp-tag\">expand &rarr; contract</span><div class=\"fp-token\">ADD full_name NULL</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-token\">пишем в обе</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-token\">бэкфилл батчами</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box mut\">DROP + NOT NULL<br>след. релиз</div></div></div>",
  "cap": "RENAME роняет ещё живой под v1: column does not exist; expand-contract держит обе версии"
 },
 "nweb-webhooks": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box acc\">raw body<br>байты</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box\">HMAC-SHA256<br>t + &quot;.&quot; + body</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-token\">MessageDigest.isEqual</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good fp-pulse-g\">200 за 50 мс</div></div><div class=\"fp-row\"><div class=\"fp-box bad\">JSON &rarr; объект<br>&rarr; обратно в JSON</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-pulse-r\">порядок ключей и пробелы<br>уехали — подпись не сошлась</div></div><div class=\"fp-row\"><span class=\"fp-tag\">реплей вчерашнего запроса</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box mut\">подпись валидна</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-blink\">t старше 300 с<br>отбой</div></div></div>",
  "cap": "HMAC по сырым байтам сходится, после ре-сериализации JSON — нет; реплей режется по t"
 },
 "ninfr-k8s--limits--j": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">limits.memory 1Gi</span><div class=\"fp-bar\"><span style=\"width:100%\"></span></div></div><div class=\"fp-row\"><div class=\"fp-box acc\">heap<br>-Xmx512m</div><div class=\"fp-box\">metaspace<br>+ code cache<br>~180m</div><div class=\"fp-box\">стеки<br>200 × 1m</div><div class=\"fp-box bad fp-pulse-r\">direct + GC<br>~250m</div></div><div class=\"fp-row\"><span class=\"fp-tag\">RSS 1.1Gi &gt; лимита</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-blink\">cgroup OOM killer<br>SIGKILL, exit 137</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box mut\">в логах пусто,<br>heap-дампа нет</div></div></div>",
  "cap": "heap 512m + non-heap ~630m = RSS 1.1Gi при лимите 1Gi → exit 137 без OutOfMemoryError"
 },
 "ninfr-k8s--graceful-": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">без preStop</span><div class=\"fp-box bad\">SIGTERM<br>t = 0</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-pulse-r\">порт закрыт<br>t = 0.1 с</div><div class=\"fp-conn\"></div><div class=\"fp-box mut\">kube-proxy и ingress<br>обновились t = 2 с</div></div><div class=\"fp-row\"><span class=\"fp-tag\">окно 1.9 с трафик ещё идёт</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-blink\">connection refused<br>502 от ingress</div></div><div class=\"fp-row\"><span class=\"fp-tag\">preStop sleep 5</span><div class=\"fp-box good\">readiness false,<br>порт открыт</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good\">дорабатывает<br>in-flight</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good fp-pulse-g\">закрылся<br>0 × 502</div></div></div>",
  "cap": "Порт закрылся на t=0.1 с, правила доехали к t=2 с — окно 502; preStop sleep 5 его убирает"
 },
 "ninfr-redis--single-": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">одна очередь</span><div class=\"fp-token\">GET</div><div class=\"fp-token\">SET</div><div class=\"fp-token bad fp-pulse-r\">KEYS session:*</div><div class=\"fp-arrow\">→</div><div class=\"fp-node acc\">1</div><span class=\"fp-tag acc\">поток</span></div><div class=\"fp-row\"><div class=\"fp-box bad big\">KEYS<br>O(N) = 10M<br>4200 мс</div><div class=\"fp-arrow\">→</div><div class=\"fp-slot bad\">GET, SET, EXPIRE ждут 4200 мс</div><div class=\"fp-token bad fp-blink\">timeout</div></div><div class=\"fp-row\"><div class=\"fp-box good\">SCAN 0<br>COUNT 500</div><div class=\"fp-conn\"></div><div class=\"fp-box good\">cursor<br>17408</div><div class=\"fp-conn\"></div><div class=\"fp-box good\">cursor 0<br>конец</div><span class=\"fp-tag good\">поток отпускается между итерациями</span></div></div>",
  "cap": "KEYS: 10M ключей за 4200 мс, вся очередь стоит; SCAN идёт курсором и отпускает поток"
 },
 "ndist-retry--amplifi": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-token acc\">1 клик</div><div class=\"fp-arrow\">→</div><div class=\"fp-box\">gateway<br>retry 3</div><div class=\"fp-arrow\">→</div><div class=\"fp-box\">BFF<br>retry 3</div><div class=\"fp-arrow\">→</div><div class=\"fp-box\">service<br>retry 3</div></div><div class=\"fp-row\"><span class=\"fp-tag\">долетело вниз</span><div class=\"fp-val\">3</div><div class=\"fp-arrow\">→</div><div class=\"fp-val\">9</div><div class=\"fp-arrow\">→</div><div class=\"fp-val bad fp-pulse-r\">27</div></div><div class=\"fp-row\"><div class=\"fp-box bad\">таймаут клиента 2 с<br>истёк на попытке 1</div><div class=\"fp-arrow\">→</div><div class=\"fp-slot mut\">26 ответов никто не ждёт</div></div><div class=\"fp-row\"><div class=\"fp-box good\">retry на 1 слое</div><div class=\"fp-token good\">backoff + jitter</div><div class=\"fp-token good\">budget 20%</div><div class=\"fp-token good\">deadline вниз</div></div></div>",
  "cap": "3×3×3 = 27 запросов в умирающий сервис, 26 ответов клиент уже не ждёт — таймаут 2 с истёк"
 },
 "ndist-consistent-has": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-token\">hash(k) = 71</div><div class=\"fp-arrow\">→</div><div class=\"fp-box\">71 % 10<br>нода 1</div><div class=\"fp-arrow\">⇄</div><div class=\"fp-box bad fp-pulse-r\">71 % 11<br>нода 5</div><div class=\"fp-val bad\">91%</div><span class=\"fp-tag bad\">промах</span></div><div class=\"fp-row\"><span class=\"fp-tag acc\">кольцо</span><div class=\"fp-node acc\">A</div><div class=\"fp-conn\"></div><div class=\"fp-node acc\">B</div><div class=\"fp-conn\"></div><div class=\"fp-node good fp-pulse-g\">new</div><div class=\"fp-conn\"></div><div class=\"fp-node acc\">C</div><div class=\"fp-val good\">9%</div></div><div class=\"fp-row\"><span class=\"fp-tag\">переехал только сегмент B→new</span><div class=\"fp-arrow\">→</div><div class=\"fp-box good\">vnodes<br>160 точек<br>на ноду</div><div class=\"fp-arrow\">→</div><div class=\"fp-slot good\">перекос ±5% вместо ±40%</div></div></div>",
  "cap": "hash%N: переход 10→11 промахивает 91% ключей, кольцо двигает один сегмент — 9%"
 },
 "ndist-kafka--partiti": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">до</span><div class=\"fp-token acc\">key=client42</div><div class=\"fp-arrow\">→</div><div class=\"fp-box\">murmur2 % 3<br>= P1</div><div class=\"fp-lane\"><div class=\"name\">P1</div><div class=\"fp-cell on\">e1</div><div class=\"fp-cell on\">e2</div><div class=\"fp-cell on\">e3</div></div></div><div class=\"fp-row\"><span class=\"fp-tag bad\">после 3→6</span><div class=\"fp-token acc\">key=client42</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad fp-pulse-r\">murmur2 % 6<br>= P4</div><div class=\"fp-lane\"><div class=\"name\">P4</div><div class=\"fp-cell on\">e4</div><div class=\"fp-cell on\">e5</div></div></div><div class=\"fp-row\"><div class=\"fp-box mut\">консьюмер A<br>P1: e2, e3</div><div class=\"fp-arrow\">⇄</div><div class=\"fp-box mut\">консьюмер B<br>P4: e4</div><div class=\"fp-arrow\">→</div><div class=\"fp-slot bad\">e4 применён раньше e3</div></div><div class=\"fp-row\"><span class=\"fp-tag\">обратно нельзя</span><div class=\"fp-ver dead\">6 → 3</div><div class=\"fp-arrow\">→</div><div class=\"fp-token bad\">InvalidPartitionsException</div></div></div>",
  "cap": "client42 уехал с P1 на P4: хвост e2,e3 ещё в P1, e4 обгоняет; 6→3 запрещено"
 },
 "ndist-virtual-thread": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">было</span><div class=\"fp-box acc\">пул 200<br>платформенных</div><div class=\"fp-arrow\">→</div><div class=\"fp-slot good\">не более 200 в БД</div><div class=\"fp-token good\">back pressure на входе</div></div><div class=\"fp-row\"><span class=\"fp-tag bad\">стало</span><div class=\"fp-box bad big\">20 000<br>virtual threads</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad fp-pulse-r\">Hikari<br>max 20</div><div class=\"fp-arrow\">→</div><div class=\"fp-slot bad\">19 980 в очереди</div></div><div class=\"fp-row\"><div class=\"fp-slot bad fp-blink\">Connection is not available, request timed out after 30000ms</div></div><div class=\"fp-row\"><div class=\"fp-box good\">Semaphore 40<br>на БД</div><div class=\"fp-box good\">Semaphore 100<br>на billing</div><div class=\"fp-arrow\">→</div><div class=\"fp-slot good\">отказ за 50 мс вместо таймаута за 30 с</div></div></div>",
  "cap": "20 000 virtual threads против Hikari max 20: очередь и timeout 30000ms вместо роста RPS"
 },
 "ninfr-metrics--cardi": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag good\">было</span><div class=\"fp-box\">method 5<br>× status 6<br>× route 40</div><div class=\"fp-arrow\">→</div><div class=\"fp-val good\">1200</div><span class=\"fp-tag\">рядов</span></div><div class=\"fp-row\"><span class=\"fp-tag bad\">+ user_id</span><div class=\"fp-box bad big\">× 500 000</div><div class=\"fp-arrow\">→</div><div class=\"fp-val bad fp-pulse-r\">600M</div><div class=\"fp-bar bad\"><span style=\"width:100%\"></span></div><span class=\"fp-tag bad\">OOMKilled</span></div><div class=\"fp-row\"><div class=\"fp-box bad\">/order/123<br>/order/124<br>/order/125</div><div class=\"fp-arrow\">⇄</div><div class=\"fp-box good\">/order/{id}<br>1 ряд</div></div><div class=\"fp-row\"><span class=\"fp-tag\">идентификаторы</span><div class=\"fp-arrow\">→</div><div class=\"fp-token acc\">логи</div><div class=\"fp-token acc\">трейсы</div><div class=\"fp-token mut\">exemplar trace_id</div></div></div>",
  "cap": "1200 рядов × user_id 500k = 600M серий и OOM; /order/123 против /order/{id} — 1 ряд"
 },
 "nspri-tx": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag acc\">@Transactional</span><div class=\"fp-box acc\">BEGIN<br>взял коннект</div><div class=\"fp-conn\"></div><div class=\"fp-box bad big fp-pulse-r\">REST<br>3 c</div><div class=\"fp-conn\"></div><div class=\"fp-box\">COMMIT<br>вернул</div></div><div class=\"fp-row\"><span class=\"fp-tag\">Hikari busy 10/10</span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-slot bad\">190 ждут, connection-timeout 30 000 мс</div></div><div class=\"fp-row\"><span class=\"fp-tag bad\">исход</span><div class=\"fp-box bad fp-blink\">Connection is not<br>available</div><div class=\"fp-arrow\">&rarr;</div><span class=\"fp-val bad\">3</span><span class=\"fp-tag mut\">rps на инстанс</span></div></div>",
  "cap": "Коннект занят все 3 с REST-вызова: 10/10 Hikari busy, потолок ~3 rps, дальше timeout"
 },
 "nspri-virtual-thread": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag mut\">было</span><div class=\"fp-box mut\">Tomcat<br>200 threads</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-slot mut\">очередь стояла здесь</div></div><div class=\"fp-row\"><span class=\"fp-tag acc\">стало</span><div class=\"fp-box acc big fp-pulse-a\">virtual<br>10 000</div><div class=\"fp-conn\"></div><div class=\"fp-box bad fp-pulse-r\">Hikari<br>max=10</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-slot bad\">очередь здесь</div></div><div class=\"fp-row\"><span class=\"fp-tag\">busy 10/10</span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><div class=\"fp-arrow\">&rarr;</div><span class=\"fp-val bad\">190</span><span class=\"fp-tag mut\">connections_pending</span></div></div>",
  "cap": "Потоков стало 10 000, но Hikari max=10 прежний — очередь переехала с Tomcat на БД"
 },
 "nspri-data": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag acc\">@Modifying update</span><div class=\"fp-conn\"></div><div class=\"fp-box mut\">мимо контекста<br>персистентности</div><div class=\"fp-conn\"></div><div class=\"fp-node good fp-pulse-g\">NEW</div></div><div class=\"fp-lane\"><div class=\"name\">Persistence Context (L1)</div><div class=\"fp-row\"><div class=\"fp-box bad\">Order#42<br>status=OLD</div><span class=\"fp-token bad\">managed</span><span class=\"fp-tag\">снапшот не обновлён</span></div></div><div class=\"fp-row\"><span class=\"fp-token\">getStatus()</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-blink\">OLD</div><span class=\"fp-tag good\">clearAutomatically</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good\">чтение идёт в БД<br>&rarr; NEW</div></div></div>",
  "cap": "UPDATE ушёл в БД (status=NEW), а order.getStatus() читает L1-кеш и отдаёт OLD"
 },
 "nspri-security": {
  "html": "<div class=\"fp-col\"><div class=\"fp-lane\"><div class=\"name\">http-nio-8080-exec-1</div><div class=\"fp-row\"><span class=\"fp-tag acc\">ThreadLocal</span><div class=\"fp-box acc\">SecurityContext<br>user=ivan</div><div class=\"fp-arrow\">&rarr;</div><span class=\"fp-token\">@Async submit</span></div></div><div class=\"fp-lane\"><div class=\"name\">task-1 (core-size=8)</div><div class=\"fp-row\"><span class=\"fp-tag bad\">ThreadLocal</span><div class=\"fp-box bad fp-pulse-r\">пусто</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad\">getAuthentication()<br>= null</div></div></div><div class=\"fp-row\"><span class=\"fp-tag good\">лечение</span><div class=\"fp-box good\">TaskDecorator</div><div class=\"fp-conn\"></div><div class=\"fp-box good\">контекст<br>перенесён явно</div></div></div>",
  "cap": "Контекст лежит в ThreadLocal exec-1, в потоке task-1 пусто: getAuthentication() = null"
 },
 "nspri-validation": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag acc\">@RestController</span><div class=\"fp-box\">@Valid<br>@RequestBody</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good\">MethodArgument<br>NotValidException</div><div class=\"fp-node good fp-pulse-g\">400</div></div><div class=\"fp-row\"><span class=\"fp-tag\">@Service без @Validated</span><div class=\"fp-box mut\">@Valid dto</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box mut fp-blink\">прокси нет —<br>проверки нет</div><div class=\"fp-node bad\">200</div></div><div class=\"fp-row\"><span class=\"fp-tag good\">@Validated на классе</span><div class=\"fp-box acc\">MethodValidation<br>Interceptor</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad\">ConstraintViolation<br>Exception</div><div class=\"fp-node bad fp-pulse-r\">500</div></div></div>",
  "cap": "@Valid в MVC даёт 400; на бине без @Validated проверки нет, с ним — 500 вместо 400"
 },
 "nspri-jpa": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag good\">DTO / проекция</span><div class=\"fp-box good\">record<br>OrderView</div><div class=\"fp-conn\"></div><div class=\"fp-box\">select new<br>OrderView(...)</div><div class=\"fp-node good fp-pulse-g\">OK</div></div><div class=\"fp-row\"><span class=\"fp-tag bad\">@Entity</span><div class=\"fp-box bad\">record<br>Order</div><div class=\"fp-conn\"></div><div class=\"fp-box bad fp-pulse-r\">нет no-arg ctor<br>класс final</div><div class=\"fp-node bad\">нет</div></div><div class=\"fp-row\"><span class=\"fp-tag\">dirty checking</span><div class=\"fp-box mut\">loaded state<br>vs текущее</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-slot bad\">у record поля final — сравнивать не с чем, следить не за чем</div></div></div>",
  "cap": "record OrderView в select new — OK; record как @Entity — нет no-arg ctor, класс final"
 },
 "njvm-containers": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">нода</span><div class=\"fp-box\">64 CPU<br>256 Гб</div><div class=\"fp-arrow\">→</div><div class=\"fp-box acc\">cgroup<br>cpu.max = 100000 100000</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad big fp-pulse-r\">available<br>Processors<br>= 1</div></div><div class=\"fp-row\"><span class=\"fp-tag\">common ForkJoinPool</span><div class=\"fp-box\">parallelism<br>= N − 1 = 0</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad\">caller-runs:<br>parallelStream()<br>в своём потоке</div></div><div class=\"fp-row\"><span class=\"fp-tag\">эргономика: &lt;2 CPU или &lt;1792 Мб</span><div class=\"fp-box mut\">G1</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad\">SerialGC<br>1 поток STW</div><div class=\"fp-val\">×4</div></div><div class=\"fp-row\"><div class=\"fp-slot\">-XX:+PrintFlagsFinal | grep UseSerialGC · availableProcessors() в поде</div></div></div>",
  "cap": "cgroup limit=1 → availableProcessors 1 → FJP parallelism 0 и SerialGC вместо G1"
 },
 "ndb-sqljoin": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">план</span><div class=\"fp-box acc\">rows=12<br>оценка</div><div class=\"fp-arrow\">→</div><div class=\"fp-box\">Nested Loop<br>+ Index Scan</div><div class=\"fp-arrow\">→</div><div class=\"fp-box good\">0.4 c</div></div><div class=\"fp-row\"><span class=\"fp-tag\">EXPLAIN ANALYZE</span><div class=\"fp-box bad fp-pulse-r\">actual rows<br>1 200 000</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad big\">1.2M ×<br>поиск по индексу</div><div class=\"fp-val\">40 c</div></div><div class=\"fp-row\"><span class=\"fp-token\">Nested Loop: мелкая внешняя + индекс справа</span><span class=\"fp-token\">Hash: хеш по меньшей, один проход</span><span class=\"fp-token\">Merge: обе стороны отсортированы</span></div><div class=\"fp-row\"><div class=\"fp-slot\">ANALYZE + CREATE STATISTICS на коррелированные колонки</div><div class=\"fp-arrow\">→</div><div class=\"fp-box good\">Hash Join<br>1.1 c</div></div></div>",
  "cap": "Оценка rows=12 против actual 1.2M: Nested Loop крутит 1.2M поисков — 40 c вместо 1 c"
 },
 "ndb-ddllocks": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">держит с t=0</span><div class=\"fp-box mut\">SELECT отчёт<br>5 мин</div><span class=\"fp-token\">ACCESS SHARE</span></div><div class=\"fp-lane\"><div class=\"name\">очередь блокировок — FIFO</div><div class=\"fp-row\"><div class=\"fp-box bad fp-pulse-r\">ALTER TABLE<br>ждёт ACCESS<br>EXCLUSIVE</div><div class=\"fp-arrow\">→</div><span class=\"fp-cell bad fp-blink\"></span><span class=\"fp-cell bad fp-blink\"></span><span class=\"fp-cell bad fp-blink\"></span><span class=\"fp-cell bad fp-blink\"></span><span class=\"fp-token\">новые SELECT/INSERT встали за ним</span></div></div><div class=\"fp-row\"><span class=\"fp-tag\">сам ALTER</span><div class=\"fp-box good\">3 мс</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad big\">простой 5 мин</div></div><div class=\"fp-row\"><div class=\"fp-slot\">SET lock_timeout='2s' + ретрай: падает миграция, а не прод</div></div></div>",
  "cap": "ALTER ждёт ACCESS EXCLUSIVE за 5-минутным SELECT, и весь новый трафик встаёт за ним"
 },
 "ndb-vacuumxmin-hor": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">txid</span><div class=\"fp-box acc fp-pulse-a\">1000<br>idle in tx · 2ч</div><div class=\"fp-conn\"></div><div class=\"fp-box mut\">1500</div><div class=\"fp-conn\"></div><div class=\"fp-box\">2000<br>сейчас</div></div><div class=\"fp-row\"><span class=\"fp-tag\">мёртвые версии строк</span><span class=\"fp-cell dead\"></span><span class=\"fp-cell dead\"></span><span class=\"fp-token\">до 1000 — убраны</span><span class=\"fp-cell bad\"></span><span class=\"fp-cell bad\"></span><span class=\"fp-cell bad\"></span><span class=\"fp-cell bad\"></span><span class=\"fp-token\">после 1000 — остаются</span></div><div class=\"fp-row\"><div class=\"fp-slot\">VACUUM: 0 removed, 4 200 000 dead row versions cannot be removed yet</div></div><div class=\"fp-row\"><span class=\"fp-tag\">bloat таблицы и индексов</span><div class=\"fp-bar\"><span style=\"width:85%\"></span></div><div class=\"fp-val\">×6</div></div></div>",
  "cap": "VACUUM: 0 removed, 4.2M dead not yet removable — снапшот idle-in-tx держит горизонт xmin"
 },
 "ndb-pkuuid": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">bigint / uuid v7</span><span class=\"fp-cell\"></span><span class=\"fp-cell\"></span><span class=\"fp-cell\"></span><span class=\"fp-cell\"></span><span class=\"fp-cell good fp-pulse-g\"></span><span class=\"fp-token\">одна горячая страница справа</span></div><div class=\"fp-row\"><span class=\"fp-tag\">uuid v4</span><span class=\"fp-cell bad fp-blink\"></span><span class=\"fp-cell\"></span><span class=\"fp-cell bad fp-blink\"></span><span class=\"fp-cell bad fp-blink\"></span><span class=\"fp-cell\"></span><span class=\"fp-token\">сплиты 50/50 по всему дереву</span></div><div class=\"fp-row\"><div class=\"fp-box acc\">16 байт<br>в каждом индексе</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad fp-pulse-r\">full-page writes<br>после checkpoint</div><div class=\"fp-arrow\">→</div><div class=\"fp-val\">WAL ×3</div></div><div class=\"fp-row\"><div class=\"fp-slot\">id нужен до записи: идемпотентность, шардинг</div><div class=\"fp-arrow\">→</div><div class=\"fp-box good\">UUIDv7</div></div></div>",
  "cap": "v4 бьёт в случайные страницы: сплиты и fpi на каждую вставку; v7 и bigint — в правый край"
 },
 "ntest-integrationtx": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">тест</span><div class=\"fp-box acc\">@Transactional:<br>одна tx на тест<br>и на сервис</div><div class=\"fp-arrow\">→</div><div class=\"fp-box mut\">rollback<br>flush не было</div><div class=\"fp-box good fp-pulse-g\">PASS</div></div><div class=\"fp-row\"><span class=\"fp-tag\">прод</span><div class=\"fp-box\">сервис открыл<br>свою tx</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad fp-pulse-r\">flush + commit:<br>констрейнты,<br>триггеры</div><div class=\"fp-box bad big\">23505</div></div><div class=\"fp-row\"><span class=\"fp-tag\">Session</span><span class=\"fp-token\">в тесте открыта до конца — lazy подгружается</span><div class=\"fp-arrow\">⇄</div><span class=\"fp-token\">в проде закрыта — LazyInitializationException</span></div><div class=\"fp-row\"><div class=\"fp-slot\">сервису своя tx · проверка после flush/clear или из нового EntityManager</div></div></div>",
  "cap": "Тест делит tx и делает rollback → PASS; в проде commit даёт 23505 и LazyInit"
 },
 "ntest-testcontainers": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag bad\">static @Container</span><div class=\"fp-box bad\">Test1IT<br>start pg</div><div class=\"fp-box bad\">Test2IT<br>start pg</div><div class=\"fp-box bad fp-pulse-r\">…×100<br>start pg</div><div class=\"fp-arrow\">→</div><div class=\"fp-val bad\">40 мин</div></div><div class=\"fp-row\"><span class=\"fp-tag acc\">singleton в базовом классе</span><div class=\"fp-box good big fp-pulse-g\">pg: 1 старт<br>на всю JVM</div><div class=\"fp-arrow\">→</div><div class=\"fp-val good\">4 мин</div></div><div class=\"fp-row\"><span class=\"fp-tag\">кэш контекстов Spring</span><div class=\"fp-token good\">та же конфигурация → hit</div><div class=\"fp-token bad\">лишний @MockBean → miss</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad\">новый Hikari<br>+ Flyway</div></div></div>",
  "cap": "100 классов × старт Postgres = 40 мин; один singleton-контейнер на JVM = 4 мин"
 },
 "ncryp-sluchaynost-i-": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box bad\">new Random(<br>currentTimeMillis)</div><div class=\"fp-arrow\">→</div><div class=\"fp-cell on\">7</div><div class=\"fp-cell on\">3</div><div class=\"fp-cell dead\">?</div><span class=\"fp-tag bad\">2 выдачи → состояние восстановлено</span></div><div class=\"fp-row\"><span class=\"fp-tag\">окно = timestamp письма ±2 с</span><div class=\"fp-val bad\">4 000</div><span class=\"fp-tag\">seed'ов перебрать</span><div class=\"fp-arrow\">→</div><div class=\"fp-box bad fp-pulse-r\">любой токен<br>сброса пароля</div></div><div class=\"fp-row\"><div class=\"fp-box good\">SecureRandom<br>/dev/urandom</div><div class=\"fp-arrow\">→</div><div class=\"fp-box good big fp-pulse-g\">32 байта<br>энтропии ОС</div></div><div class=\"fp-row\"><span class=\"fp-tag\">6-значный OTP</span><div class=\"fp-val\">10⁶</div><div class=\"fp-arrow\">→</div><div class=\"fp-token acc\">держится на rate limit и TTL 5 мин</div></div></div>",
  "cap": "Окно seed'а — 4 000 мс от времени письма; 2 выдачи Random, и токен сброса вычислен"
 },
 "ncryp-ataki-na-reali": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag bad\">equals()</span><div class=\"fp-cell on\">a</div><div class=\"fp-cell on\">3</div><div class=\"fp-cell bad fp-blink\">x</div><div class=\"fp-cell mut\">·</div><div class=\"fp-cell mut\">·</div><div class=\"fp-arrow\">→</div><div class=\"fp-val bad\">3</div><span class=\"fp-tag\">сравнения</span></div><div class=\"fp-row\"><span class=\"fp-tag bad\">угадан ещё символ</span><div class=\"fp-cell on\">a</div><div class=\"fp-cell on\">3</div><div class=\"fp-cell on\">f</div><div class=\"fp-cell bad fp-blink\">x</div><div class=\"fp-cell mut\">·</div><div class=\"fp-arrow\">→</div><div class=\"fp-val bad\">4</div><span class=\"fp-tag\">дольше</span></div><div class=\"fp-row\"><span class=\"fp-tag\">16 вариантов × 64 позиции</span><div class=\"fp-val bad\">1024</div><span class=\"fp-tag bad\">серии замеров → подпись собрана</span></div><div class=\"fp-row\"><span class=\"fp-tag good\">MessageDigest.isEqual</span><div class=\"fp-box good big fp-pulse-g\">XOR всех 32 байт<br>время = const</div></div></div>",
  "cap": "equals() встаёт на 3-м байте, потом на 4-м: 1024 серии замеров — и подпись собрана"
 },
 "nbuil-maven": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag bad\">mvn test</span><div class=\"fp-box acc\">test<br>surefire *Test</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad fp-pulse-r\">fail в конце<br>фазы test</div><div class=\"fp-token bad\">*IT не запускались вообще</div></div><div class=\"fp-row\"><span class=\"fp-tag acc\">mvn verify</span><div class=\"fp-box\">pre-int<br>up</div><div class=\"fp-arrow\">→</div><div class=\"fp-box acc\">integration-test<br>failsafe *IT: fail</div><div class=\"fp-arrow\">→</div><div class=\"fp-box good\">post-int<br>down</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad\">verify<br>падает тут</div></div><div class=\"fp-row\"><span class=\"fp-tag bad\">цель verify не объявлена</span><div class=\"fp-box mut\">failsafe-summary.xml<br>никто не читает</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad fp-blink\">билд зелёный<br>при упавших IT</div></div></div>",
  "cap": "mvn test не видит *IT; на verify failsafe сперва гасит контейнеры, потом валит билд"
 },
 "nbuil-vosproizvodimo": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">коммит a1b2c3d, диффа нет</span><div class=\"fp-box good\">вчера<br>зелёная</div><div class=\"fp-arrow\">⇄</div><div class=\"fp-box bad fp-blink\">сегодня<br>красная</div></div><div class=\"fp-row\"><div class=\"fp-ver\">lib 1.4.0-SNAPSHOT</div><div class=\"fp-arrow\">→</div><div class=\"fp-box mut\">-20260813<br>.101533-116</div><div class=\"fp-arrow\">⇄</div><div class=\"fp-box bad fp-pulse-r\">-20260814<br>.101533-117</div></div><div class=\"fp-row\"><div class=\"fp-ver\">temurin:17</div><div class=\"fp-arrow\">→</div><div class=\"fp-box mut\">17.0.11</div><div class=\"fp-arrow\">⇄</div><div class=\"fp-box bad fp-pulse-r\">17.0.12</div></div><div class=\"fp-row\"><span class=\"fp-tag acc\">прибить входы</span><div class=\"fp-token good\">релизная версия</div><div class=\"fp-token good\">image@sha256</div><div class=\"fp-token good\">mvnw + toolchains</div></div></div>",
  "cap": "Коммит a1b2c3d тот же, но SNAPSHOT стал -117, а temurin:17 — уже 17.0.12: билд красный"
 },
 "ndevo-ci-cd": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box bad\">CI job<br>kubectl apply</div><div class=\"fp-arrow\">→</div><div class=\"fp-box\">кластер<br>replicas=3</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad fp-pulse-r\">руками<br>scale=1</div><span class=\"fp-tag bad\">дрейф, сверять некому</span></div><div class=\"fp-row\"><span class=\"fp-tag\">креды прод-кластера</span><div class=\"fp-token bad\">лежат в CI</div><div class=\"fp-arrow\">⇄</div><div class=\"fp-token good\">только push образа</div></div><div class=\"fp-row\"><div class=\"fp-box good\">git desired<br>replicas=3</div><div class=\"fp-conn\"></div><div class=\"fp-box acc fp-pulse-a\">агент в кластере<br>reconcile 180s</div><div class=\"fp-arrow\">→</div><div class=\"fp-box good fp-pulse-g\">Synced<br>дрейф снят</div></div></div>",
  "cap": "Ручной scale=1 при push живёт незаметно; агент сверяет с git раз в 180 с и вернёт 3"
 },
 "narhi-granicy-i-kont": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag acc\">договорились</span><div class=\"fp-box acc\">domain</div><div class=\"fp-arrow\">→</div><div class=\"fp-box mut\">без Spring<br>без JPA</div></div><div class=\"fp-row\"><span class=\"fp-tag\">через 6 месяцев</span><div class=\"fp-box\">domain/Order</div><div class=\"fp-arrow\">→</div><div class=\"fp-box bad fp-pulse-r\">import jakarta.<br>persistence.Entity</div></div><div class=\"fp-row\"><span class=\"fp-slot mut\">code review: 42 файла в диффе, глаз замылен</span><div class=\"fp-arrow\">→</div><span class=\"fp-token bad\">прошло</span></div><div class=\"fp-row\"><div class=\"fp-box good fp-pulse-g\">@ArchTest noClasses()<br>..domain.. → spring</div><div class=\"fp-arrow\">→</div><span class=\"fp-token good\">BUILD FAILURE</span></div></div>",
  "cap": "domain импортнул jakarta.persistence: ревью пропустило, ArchUnit валит сборку"
 },
 "nquar-testy": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag acc\">@QuarkusTest</span><div class=\"fp-box big acc\">одна JVM:<br>тест + приложение</div><div class=\"fp-arrow\">⇄</div><span class=\"fp-token good\">@Inject / @InjectMock</span></div><div class=\"fp-row\"><span class=\"fp-tag\">@QuarkusIntegrationTest</span><div class=\"fp-box\">JVM теста</div><div class=\"fp-conn\"></div><div class=\"fp-box acc\">quarkus-run.jar<br>native / container</div></div><div class=\"fp-row\"><span class=\"fp-token bad fp-pulse-r\">@InjectMock: бина тут нет</span><div class=\"fp-arrow\">→</div><span class=\"fp-slot mut\">только RestAssured по HTTP, порт 8081</span></div><div class=\"fp-row\"><span class=\"fp-tag\">@TestProfile</span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><span class=\"fp-cell on\"></span><div class=\"fp-arrow\">→</div><span class=\"fp-token bad\">3 рестарта Quarkus</span></div></div>",
  "cap": "@QuarkusTest — одна JVM и @InjectMock; @QuarkusIT — артефакт снаружи, только HTTP"
 },
 "nquar-rest-client": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag bad\">руками</span><div class=\"fp-box bad\">HttpClient.send<br>http://orders:8080</div><div class=\"fp-arrow\">→</div><span class=\"fp-token bad fp-pulse-r\">URL в коде, таймаута нет</span></div><div class=\"fp-row\"><span class=\"fp-tag acc\">@RegisterRestClient</span><div class=\"fp-box big acc\">interface OrderApi<br>@GET /orders/{id}</div><div class=\"fp-arrow\">→</div><div class=\"fp-box mut\">impl генерит<br>сборка</div></div><div class=\"fp-row\"><span class=\"fp-slot\">quarkus.rest-client.order-api.read-timeout=2000</span><div class=\"fp-arrow\">→</div><span class=\"fp-token good\">@Retry @CircuitBreaker</span></div><div class=\"fp-row\"><span class=\"fp-token\">HTTP 409</span><div class=\"fp-arrow\">→</div><div class=\"fp-box bad\">WebApplication<br>Exception</div><div class=\"fp-arrow\">→</div><div class=\"fp-box good\">ResponseExceptionMapper<br>OrderConflict</div></div></div>",
  "cap": "Слева HttpClient с зашитым URL без таймаута, справа OrderApi: конфиг, @Retry, маппер"
 },
 "ngit-force-push": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">origin/feature</span><div class=\"fp-node\">B</div><div class=\"fp-conn\"></div><div class=\"fp-node good fp-pulse-g\">C</div><span class=\"fp-token good\">коммит коллеги</span></div><div class=\"fp-row\"><span class=\"fp-tag bad\">--force</span><div class=\"fp-node acc\">B′</div><div class=\"fp-arrow\">→</div><div class=\"fp-node mut\">C</div><span class=\"fp-token bad fp-pulse-r\">unreachable</span></div><div class=\"fp-row\"><span class=\"fp-tag good\">--force-with-lease</span><div class=\"fp-box\">origin/feature<br>всё ещё B?</div><div class=\"fp-arrow\">→</div><span class=\"fp-token good\">rejected: stale info</span></div><div class=\"fp-row\"><span class=\"fp-slot bad\">но автофетч IDE переписал origin/feature на C</span><div class=\"fp-arrow\">→</div><span class=\"fp-token bad fp-blink\">lease пройден, C стёрт</span></div></div>",
  "cap": "--force стирает коммит C; lease сверяет origin/feature, но git fetch обновляет расписку"
 },
 "ngit-internals": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box acc big\">commit a1b2c3</div><div class=\"fp-arrow\">→</div><div class=\"fp-box\">tree</div><div class=\"fp-arrow\">→</div><div class=\"fp-box mut\">blob README<br>blob App.java</div></div><div class=\"fp-row\"><span class=\"fp-tag\">правим App.java</span><div class=\"fp-box acc\">commit d4e5f6</div><div class=\"fp-arrow\">→</div><div class=\"fp-box\">tree′</div><div class=\"fp-arrow\">→</div><div class=\"fp-box mut\">тот же blob README<br>новый blob App.java</div></div><div class=\"fp-row\"><span class=\"fp-slot mut\">diff нигде не лежит: git show считает его из двух tree</span></div><div class=\"fp-row\"><span class=\"fp-tag bad\">rebase</span><span class=\"fp-ver dead\">a1b2c3</span><div class=\"fp-arrow\">→</div><span class=\"fp-ver good fp-pulse-g\">7c1a0b</span><span class=\"fp-token mut\">старый живёт в reflog 90 дней</span></div></div>",
  "cap": "Коммит = tree + parent; README переиспользует тот же blob, rebase даёт новый SHA"
 },
 "nalgo-sorting": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">компаратор</span><div class=\"fp-node acc\">a</div><div class=\"fp-arrow\">→</div><div class=\"fp-node acc\">b</div><div class=\"fp-arrow\">→</div><div class=\"fp-node acc\">c</div><div class=\"fp-arrow\">→</div><div class=\"fp-node bad fp-pulse-r\">a</div></div><div class=\"fp-row\"><span class=\"fp-tag good\">n = 31</span><div class=\"fp-box good\">binarySort целиком<br>слияний нет</div><div class=\"fp-arrow\">→</div><span class=\"fp-token good\">тест зелёный</span></div><div class=\"fp-row\"><span class=\"fp-tag bad\">n = 32</span><div class=\"fp-box bad fp-pulse-r\">minRun 16 + merge<br>инвариант рухнул</div><div class=\"fp-arrow\">→</div><span class=\"fp-slot bad\">IllegalArgumentException: Comparison method violates its general contract!</span></div><div class=\"fp-row\"><span class=\"fp-slot mut\">источник: a.count - b.count около Integer.MAX_VALUE</span><div class=\"fp-arrow\">→</div><span class=\"fp-token bad\">переполнение</span></div></div>",
  "cap": "Цикл a→b→c→a: на 31 элементе тихо, на 32 mergeHi кидает violates general contract"
 },
 "nalgo-sorting-2": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-box bad\">файл 100 ГБ<br>целиком в RAM</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad big fp-pulse-r\">OOM</div><span class=\"fp-tag bad\">heap 4 ГБ</span></div><div class=\"fp-row\"><span class=\"fp-tag acc\">runs по 2 ГБ</span><div class=\"fp-box good\">run 1<br>сортирован</div><div class=\"fp-box good\">run 2</div><div class=\"fp-box mut\">&hellip;</div><div class=\"fp-box good\">run 50</div></div><div class=\"fp-row\"><div class=\"fp-token\">голова 1</div><div class=\"fp-token\">голова 2</div><div class=\"fp-token mut\">&hellip;</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box acc fp-pulse-a\">min-heap<br>k = 50</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-slot good\">выход отсортирован за один проход</div></div><div class=\"fp-row\"><span class=\"fp-tag\">в RAM: 50 записей + буферы</span><div class=\"fp-arrow\">&#8644;</div><span class=\"fp-tag good\">O(n log k)</span></div></div>",
  "cap": "100 ГБ целиком → OOM; 50 кусков по 2 ГБ + min-heap на 50 голов → слияние за один проход"
 },
 "nalgo-hashing": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><div class=\"fp-token\">\"ORD-2026-0814\".hashCode()</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad\">-1304264694<br>% 16 = -6</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-pulse-r\">ArrayIndex<br>OutOfBounds</div></div><div class=\"fp-row\"><span class=\"fp-tag acc\">Math.floorMod(h, 16)</span><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-cell on\">10</div><div class=\"fp-slot good\">индекс всегда 0&hellip;15</div></div><div class=\"fp-row\"><span class=\"fp-tag\">ключ без hashCode</span><div class=\"fp-box mut\">identity hash<br>@6d06d69c</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box acc\">шард 3</div><span class=\"fp-tag bad\">рестарт JVM</span><div class=\"fp-box bad fp-blink\">шард 11</div></div><div class=\"fp-row\"><span class=\"fp-tag good\">String / Integer / Long — хеш в спеке</span><div class=\"fp-arrow\">&#8644;</div><span class=\"fp-tag bad\">Object, enum — mark word</span></div></div>",
  "cap": "hashCode % 16 = −6 → AIOOBE; identity hash: после рестарта ключ уехал с шарда 3 на 11"
 },
 "nconc-vthreads": {
  "html": "<div class=\"fp-col\"><div class=\"fp-row\"><span class=\"fp-tag\">было</span><div class=\"fp-box acc\">пул<br>200</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-slot mut\">очередь ждёт — это и был backpressure</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box good\">наружу &le; 200</div></div><div class=\"fp-row\"><span class=\"fp-tag bad\">стало</span><div class=\"fp-box bad big fp-pulse-r\">20 000<br>vthreads</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad\">Hikari max 10<br>19 990 ждут</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-box bad fp-blink\">Connection is not<br>available, 30000ms</div></div><div class=\"fp-row\"><span class=\"fp-tag good\">лечение</span><div class=\"fp-box good\">Semaphore(50)</div><div class=\"fp-arrow\">&rarr;</div><div class=\"fp-slot good\">лимит на ресурс, а не на число потоков</div></div></div>",
  "cap": "Пул 200 был лимитом; 20 000 vthreads → Hikari max 10 → «not available after 30000ms»"
 }
});
