/* Какие карточки дрила относятся к теме лестницы. window.ZDRILL: тема → [класс, регулярка]. */
window.ZDRILL = {
"Java: первая строка":["Java","java|jvm|classpath|пакет"],
"Java: типы":["Java","string|equals|==|примитив|autobox|null"],
"Java: объекты":["Java","класс|интерфейс|наследован|полиморф|конструктор"],
"Java: коллекции":["Java","list|map|set|коллекц|hashmap"],
"Java: исключения":["Java","исключен|exception|try|finally"],
"Java: современное":["Java","stream|лямбд|optional|record|дженерик"],
"Java 17 → 21":["Java","sealed|record|pattern|switch|var"],
"Java: как исполняется":["JVM","байткод|jit|компиляц|интерпрет"],
"Память":["JVM","стек|куча|память|ссылк"],
"Сборка мусора":["JVM","gc|сборщик|куча|heap|oom"],
"Профилирование":["JVM","профил|dump|jfr|утечк"],
"Многопоточность":["Concurrency",""],
"java.util.concurrent":["Concurrency","executor|future|atomic|concurrenthashmap|пул"],
"Virtual threads":["Concurrency","виртуальн|virtual|threadlocal|carrier"],
"Базы данных":["DB",""],
"PostgreSQL":["DB","postgres|mvcc|vacuum|explain|пул соединен"],
"Данные под нагрузкой":["DB","реплик|шард|партицион|блокировк|batch"],
"Hibernate и JPA":["Spring","hibernate|jpa|lazy|n\\+1|entity"],
"Spring: зачем":["Spring","бин|bean|контекст|инъекц|di"],
"Spring Boot":["Spring","boot|автоконфиг|стартер|actuator"],
"Spring в работе":["Spring","controller|repository|transactional|слой"],
"Транзакции Spring":["Spring","transactional|propagation|rollback"],
"Quarkus":["Quarkus",""],
"Очереди":["Distributed","очеред|брокер|идемпотент"],
"Kafka":["Distributed","kafka|партиц|consumer|offset"],
"События и интеграция":["Архитектура","outbox|saga|event|cqrs|cdc"],
"Кэш":["Infra","кэш|cache|ttl"],
"Redis":["Infra","redis"],
"Elasticsearch":["Infra",""],
"Docker":["DevOps","docker|контейнер|образ|слой"],
"Kubernetes":["DevOps","kubernetes|k8s|под|pod|deployment"],
"Облако":["DevOps","облак|cloud|managed"],
"AWS":["DevOps","aws|s3|lambda|ec2"],
"Выкатка":["DevOps","ci|cd|деплой|релиз|откат"],
"Наблюдаемость":["DevOps","лог|метрик|трейс"],
"Prometheus и Grafana":["DevOps","prometheus|grafana|метрик"],
"Сеть":["Web","tcp|http|dns|tls|сеть"],
"API и REST":["Web","rest|http|api|идемпотент"],
"Безопасность":["Web","xss|инъекц|пароль|секрет|csrf"],
"Keycloak и OAuth2":["Web","jwt|oauth|токен|keycloak"],
"Отказоустойчивость":["Архитектура","таймаут|ретрай|circuit|отказоустойч"],
"Архитектура":["Архитектура",""],
"SOLID":["Design","solid|принцип|srp"],
"Паттерны":["Design","паттерн|фабрик|стратег|синглтон"],
"Тестирование":["Testing",""],
"Git":["Git",""],
"Сложность":["Algorithms","сложност|o\\(|алгоритм"],
"Отладка":["Java","стектрейс|отладк|debug"]
};
